import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {seed,get,money,tags,eventNames,people,sum,used,remainder,recovered,capacity,allocate,connect,assignIncome,share,tagAmount,transfer,unlink,linked,ready,stats,addBatch,batchApply,suggestible} from './model.mjs';
import './style.css';

function Amount({label,value,onChange}){const [text,setText]=useState((value/100).toFixed(2));useEffect(()=>setText((value/100).toFixed(2)),[value]);function commit(){if(/^\d+(\.\d{0,2})?$/.test(text))onChange(Math.round(Number(text)*100));setText((value/100).toFixed(2));}return <label className="amount"><span>$</span><input aria-label={label} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.target.blur();if(e.key==='Escape'){setText((value/100).toFixed(2));e.target.blur();}}}/></label>}
const Badge=({children,tone=''})=><span className={'badge '+tone}>{children}</span>;
function App(){
 const [state,setState]=useState(seed),[history,setHistory]=useState([]),[selected,setSelected]=useState('alex'),[layout,setLayout]=useState('Focus'),[panel,setPanel]=useState('Connections'),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[targetSearch,setTargetSearch]=useState(''),[notice,setNotice]=useState(''),[guide,setGuide]=useState(false),[batch,setBatch]=useState(false),[checked,setChecked]=useState([]),[showFiled,setShowFiled]=useState(false);
 const r=get(state,selected)||state.rows[0],totals=stats(state),pair=linked(state,r.id);
 const outgoing=r.amount<0,expense=outgoing&&r.kind!=='settlement',payable=r.kind==='payable';
 const choices=pair?['Connection','Context']:payable?['Shares','Payments','Context']:r.kind==='settlement'?['Connections','Context']:outgoing?['Tags','Shares','Money back','Context']:['Connections','Income','Transfer','Context'];
 const active=choices.includes(panel)?panel:choices[0];
 const visible=state.rows.filter(x=>(showFiled||!x.done)&&(!search||`${x.name} ${x.account} ${x.person||''}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='All'||filter==='Money in'&&x.amount>0&&x.kind!=='payable'||filter==='Money out'&&x.amount<0||filter==='Owed'&&x.kind==='payable'||filter==='Suggestions'&&x.suggestedTag));
 const index=visible.findIndex(x=>x.id===r.id),routine=state.rows.filter(suggestible);
 function change(fn,label){try{const next=structuredClone(state);fn(next);setHistory(h=>[...h.slice(-39),state]);setState(next);setNotice(label);}catch(e){setNotice(e.message);}}
 function open(id){setSelected(id);setTargetSearch('');setPanel('Connections');}
 function undo(){if(history.length){setState(history.at(-1));setHistory(h=>h.slice(0,-1));setNotice('Last change undone.');}}
 function file(){const next=visible[(index+1)%visible.length];change(s=>{const row=get(s,r.id);if(!ready(s,row))throw Error('There is still an unallocated amount. You can leave it open and return later.');row.done=true;},'Filed. The relationships remain editable.');if(layout==='Focus'&&next&&next.id!==r.id)open(next.id);}
 function addTarget(id){change(s=>connect(s,r.id,id),'Connected. Adjust the amount in the rail.');}
 const targetRows=state.rows.filter(t=>(t.id!==r.id)&&capacity(state,r,t)>0&&!r.allocations.some(a=>a.id===t.id)&&(!targetSearch||`${t.name} ${t.event||''}`.toLowerCase().includes(targetSearch.toLowerCase())));
 const allocationTotal=sum(r.allocations),incomeAmount=r.income,remaining=remainder(r);
 const received=state.rows.filter(x=>x.allocations.some(a=>a.id===r.id));
 function amountRows(){return <div className="allocation-grid">{r.allocations.map((a,i)=><div className="allocation" key={a.id} style={{'--accent':['#c5bfdd','#e2c7ae','#b7cdbe'][i%3]}}><button className="allocation-name" onClick={()=>open(a.id)} title="Open linked record">{get(state,a.id).name} ↗</button><Amount label={'Allocation to '+get(state,a.id).name} value={a.cents} onChange={n=>change(s=>allocate(s,r.id,a.id,n),'Allocation updated.')}/><button className="x" aria-label={'Disconnect '+get(state,a.id).name} onClick={()=>change(s=>allocate(s,r.id,a.id,0),'Connection removed. Money is available again.')}>×</button></div>)}{incomeAmount>0&&<div className="allocation" style={{'--accent':tags[r.incomeTag]}}><span>{r.incomeTag} income</span><strong>{money(incomeAmount)}</strong><button className="x" aria-label="Remove income allocation" onClick={()=>change(s=>{get(s,r.id).income=0;get(s,r.id).incomeTag='';get(s,r.id).done=false;},'Income portion released.')}>×</button></div>}</div>}
 function incomingConnections(){return <><div className="section-line"><span>Allocate this payment</span><Badge tone={remaining?'warm':'green'}>{money(remaining)} available</Badge></div><div className="rail" aria-label="Payment allocation">{r.allocations.map((a,i)=><span key={a.id} style={{width:a.cents/Math.abs(r.amount)*100+'%',background:['#c5bfdd','#e2c7ae','#b7cdbe'][i%3]}}/>)}<span style={{width:incomeAmount/Math.abs(r.amount)*100+'%',background:tags[r.incomeTag]}}/><span className="remainder" style={{flex:1}}/></div>{amountRows()}{!r.allocations.length&&<div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addTarget(e.dataTransfer.getData('text/plain'));}}>Drop an expense here, or add one below.</div>}<div className="section-line library-head"><span>{r.kind==='settlement'?'Outstanding payables':'Expenses to connect'}</span>{r.person&&<Badge>{r.person}’s available shares</Badge>}</div><input className="search" aria-label="Find connection" placeholder="Find an expense or event…" value={targetSearch} onChange={e=>setTargetSearch(e.target.value)}/><div className="event-shortcuts">{eventNames.map(ev=>{const eligible=targetRows.filter(t=>t.event===ev);return eligible.length>0&&<button key={ev} disabled={!remaining} onClick={()=>change(s=>{for(const t of eligible)connect(s,r.id,t.id);},'Filled remaining shares, oldest listed first. Each amount is editable.')}>＋ {ev} <small>{eligible.length}</small></button>})}</div><div className="candidates">{targetRows.map(t=><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)} className="candidate" key={t.id} disabled={!remaining} onClick={()=>addTarget(t.id)}><span className="candidate-icon">{t.kind==='payable'?'↗':'↙'}</span><span><b>{t.name}</b><small>{t.event||'No event'} · {t.date.slice(5)} · {t.account}</small></span><span className="right"><b>{money(capacity(state,r,t))}</b><small>available ＋</small></span></button>)}{targetRows.length===0&&<p className="empty">No other eligible expenses. Existing connections are editable above.</p>}</div>{remaining>0&&r.kind!=='settlement'&&<button className="subtle remainder-action" onClick={()=>setPanel('Income')}>Classify the remaining {money(remaining)} as income →</button>}<p className="micro">Event shortcuts add distinct expenses once. Their membership never moves money on its own.</p></>}
 function tagEditor(){const portions=r.tags.length?r.tags:[{id:'Other',cents:Math.abs(r.amount)}];return <><div className="section-line"><span>What this purchase contains</span>{!r.tags.length&&<button className="text-button" onClick={()=>change(s=>{get(s,r.id).tags=[{id:'Other',cents:Math.abs(r.amount)}];},'Other explicitly accepted.')}>Keep Other</button>}<button className="text-button" onClick={()=>change(s=>{get(s,r.id).tags=[];get(s,r.id).done=false;},'Tags reset to Other.')}>Reset</button></div><div className="rail">{portions.map(t=><span key={t.id} style={{width:t.cents/Math.abs(r.amount)*100+'%',background:tags[t.id]}}/>)}</div><div className="allocation-grid">{portions.map(t=><div className="allocation" key={t.id} style={{'--accent':tags[t.id]}}><span>{t.id}</span>{t.id==='Other'?<strong>{money(t.cents)}</strong>:<Amount label={t.id+' amount'} value={t.cents} onChange={n=>change(s=>tagAmount(s,r.id,t.id,n),'Tag amount updated.')}/ >}{t.id!=='Other'&&<button className="x" aria-label={'Remove '+t.id} onClick={()=>change(s=>tagAmount(s,r.id,t.id,0),'Released to Other.')}>×</button>}</div>)}</div><div className="tag-library">{['Lodging','Dining','Groceries','Home'].filter(t=>!portions.some(p=>p.id===t)).map(t=><button style={{'--accent':tags[t]}} key={t} onClick={()=>change(s=>{const row=get(s,r.id),free=row.tags.find(p=>p.id==='Other')?.cents??(row.tags.length?0:Math.abs(row.amount));if(!free)throw Error('Lower an existing tag amount to make room for another.');tagAmount(s,r.id,t,free);},'Tag added. Edit its amount to leave room for another.')}>＋ {t}</button>)}</div><p className="micro">Lower a tag amount to release a remainder into Other; add another tag to use it. These amounts describe the original purchase, before repayments.</p></>}
 function sharesEditor(){const assigned=Object.values(r.shares).reduce((a,b)=>a+b,0),whole=Math.abs(r.amount);return <><div className="section-line"><span>Agreed responsibility</span><button className="text-button" onClick={()=>change(s=>{const row=get(s,r.id),n=Math.floor(whole/3);for(const p of people){const paid=recovered(s,r.id,p);if(paid>n)throw Error('Equal shares would invalidate an existing repayment.');}row.shares={Me:n+whole%3,Alex:n,Maya:n};row.done=false;},'Shared equally between three people.')}>Split equally</button></div><div className="share-list">{people.map((p,i)=><div className="share-row" key={p}><span className={'avatar av'+i}>{p[0]}</span><span><b>{p}</b><small>{payable?(p==='Me'?'Your payable to '+r.person:p===r.person?'Paid the original bill':'Outside your accounts'):p==='Me'?'Your agreed cost':money(recovered(state,r.id,p))+' received'}</small></span><Amount label={'Share for '+p} value={r.shares[p]||0} onChange={n=>change(s=>share(s,r.id,p,n),'Responsibility updated; no money moved.')}/></div>)}</div><p className={'balance-note '+(whole!==assigned?'warm':'')}>{whole===assigned?'All '+money(whole)+' assigned':money(whole-assigned)+' responsibility not assigned'}</p><p className="micro">An agreement records who owes what. It does not count as a repayment. To move an amount, lower one share, then increase another.</p></>}
 function moneyBack(){const incoming=state.rows.filter(s=>s.id!==r.id&&capacity(state,s,r)>0&&remainder(s)>0&&!s.allocations.some(a=>a.id===r.id));return <><div className="section-line"><span>{payable?'Payments toward your share':'Payments connected to this expense'}</span><Badge>{money(recovered(state,r.id))} {payable?'settled':'received'}</Badge></div>{received.map(source=>{const a=source.allocations.find(a=>a.id===r.id);return <div className="payment-row" key={source.id}><button className="text-button" onClick={()=>open(source.id)}>{source.name} ↗</button><Amount label={'Received from '+source.name} value={a.cents} onChange={n=>change(s=>allocate(s,source.id,r.id,n),'Connection updated from the expense side.')}/><button className="x" aria-label={'Remove payment '+source.name} onClick={()=>change(s=>allocate(s,source.id,r.id,0),'Payment disconnected.')}>×</button></div>})}{incoming.map(source=><button key={source.id} className="candidate" onClick={()=>change(s=>connect(s,source.id,r.id),'Connected the available amount.')}><span className="candidate-icon">＋</span><span><b>{source.name}</b><small>{source.person} · {source.date.slice(5)}</small></span><span className="right"><b>{money(Math.min(remainder(source),capacity(state,source,r)))}</b><small>connect</small></span></button>)}{!received.length&&!incoming.length&&<p className="empty">No eligible payment yet. The amount owed remains visible in People.</p>}<p className="micro">This edits the same connection as the payment card. It never creates a second repayment.</p></>}
 function incomeEditor(){return <><div className="section-line"><span>Income portion</span><Badge>{money(Math.abs(r.amount)-allocationTotal)}</Badge></div><p className="muted">Keep expense repayments connected. Classify only what remains.</p>{amountRows()}<div className="tag-library">{['Salary','Gift','Other'].map(t=><button key={t} className={r.incomeTag===t?'selected':''} style={{'--accent':tags[t]}} disabled={Math.abs(r.amount)===allocationTotal} onClick={()=>change(s=>assignIncome(s,r.id,t),'Remaining amount classified as '+t+'.')}>{t}</button>)}</div><p className="micro">Unallocated money stays unresolved until you deliberately classify it.</p></>}
 function transferEditor(){if(pair){const other=get(state,pair.in===r.id?pair.out:pair.in);return <><div className="transfer-pair"><span>{get(state,pair.out).account}</span><strong>→</strong><span>{get(state,pair.in).account}</span></div><div className="candidate"><span><b>{other.name}</b><small>{other.date} · other side of this movement</small></span><b>{money(other.amount)}</b></div><div className="impact"><span>Internal principal <b>{money(get(state,pair.in).amount)}</b></span><span>External fee <b>{money(pair.fee)}</b></span></div><button className="subtle" onClick={()=>change(s=>unlink(s,r.id),'Pair unlinked. Both records are open again.')}>Unlink transfer</button></>}
 const candidates=state.rows.filter(t=>t.amount<0&&t.account!==r.account&&!linked(state,t.id)&&t.kind!=='settlement'&&!Object.keys(t.shares).length&&Math.abs(Math.abs(t.amount)-r.amount)<=r.amount*.1);
 return <><div className="section-line"><span>Outgoing matches · within 10%</span><Badge>Other accounts</Badge></div>{candidates.map(t=><div className="transfer-option" key={t.id}><div className="candidate"><span className="candidate-icon">⇄</span><span><b>{t.name}</b><small>{t.account} · {t.date}</small></span><b>{money(t.amount)}</b></div><div className="impact"><span>{money(r.amount)} internal</span><span>{money(Math.abs(t.amount)-r.amount)} fee</span><button className="primary" disabled={!!used(r)||recovered(state,t.id)>0} onClick={()=>change(s=>transfer(s,r.id,t.id),'Transfer linked. Principal is excluded from income and spending.')}>Link & accept fee</button></div></div>)}{!candidates.length&&<p className="empty">No eligible counterpart in this sample. An unmatched transfer must stay open.</p>}<p className="micro">Amount similarity is a suggestion. Linking explicitly accepts the displayed fee.</p></>}
 function contextEditor(){return <><div className="section-line"><span>Event membership</span><Badge>Organizational only</Badge></div><div className="tag-library">{[null,...eventNames].map(ev=><button className={r.event===ev?'selected':''} key={ev||'none'} onClick={()=>change(s=>{get(s,r.id).event=ev;},ev?'Added to '+ev+'. Existing money connections unchanged.':'Event removed; connections preserved.')}>{ev||'No event'}</button>)}</div><div className="source"><small>ORIGINAL SAMPLE RECORD</small><dl><dt>Date</dt><dd>{r.date}</dd><dt>Account</dt><dd>{r.account}</dd><dt>Amount</dt><dd>{money(r.amount)}</dd><dt>Origin</dt><dd>{payable?'Manually recorded bill paid by someone else':'Synthetic account entry'}</dd></dl></div></>}
 const tasks=[['Link the savings movement','Match +$500 to −$502. Inspect the $2 fee.'],['Handle one mixed receipt','Alex’s $275 covers $200 cabin, $60 dinner, $10 groceries and a $5 gift.'],['Leave a genuine outstanding balance','Maya’s $200 covers $150 cabin and $50 dinner. Alex still owes $30; Maya still owes $60.'],['Separate owing from paying','Maya paid $90 for tickets. Your share is $30; connect your outgoing $30 to settle it.'],['Split a purchase, then scale up','Set Superstore to $80 Groceries / $40 Home. Load 120 routine items and preview their suggestions together.']];
 return <div className="app"><header><div className="brand"><span className="brand-mark">u.</span><div><b>Urbanomics</b><small>Relationship study / 01</small></div></div><div className="layout-switch" aria-label="Workspace layout">{['Focus','Desk'].map(x=><button aria-pressed={layout===x} key={x} onClick={()=>setLayout(x)}>{x==='Focus'?'▣':'▤'} {x}</button>)}</div><div className="top-actions"><Badge>Sample data · session only</Badge><button className="subtle" onClick={()=>setGuide(!guide)}>{guide?'Close exercise':'The exercise'}</button><button className="icon-button" aria-label="Undo" disabled={!history.length} onClick={undo}>↶</button><button className="text-button" onClick={()=>{setHistory(h=>[...h,state]);setState(seed());open('alex');setNotice('Reset the sample. Undo restores your previous working copy.');}}>Reset</button></div></header>
 <section className="intro"><div><span className="eyebrow">A WORKSPACE, NOT A QUESTIONNAIRE</span><h1>Give the money its context.</h1><p>Connect, divide, revisit. Work from either side of a relationship.</p></div><button className="subtle" disabled={state.batchAdded} onClick={()=>change(addBatch,'120 routine transactions added. Open suggestions to review them in a batch.')}>{state.batchAdded?'120 routine items loaded':'＋ Load 120 routine items'}</button></section>
 {guide&&<section className="guide"><div><h2>A weekend with loose ends.</h2><p>Try the same tasks in both layouts. Switch freely; your working copy stays with you. File only when you want an item out of the queue.</p><p>Focus keeps one record in view. Desk keeps the surrounding records and balances visible. Neither tells you which step to take next.</p></div><ol>{tasks.map(([title,body])=><li key={title}><b>{title}</b><span>{body}</span></li>)}</ol></section>}
 <section className="summary"><div><small>Expense cash still fronted</small><b>{money(totals.fronted)}</b><span>Provisional until transfers are linked</span></div><div><small>Repayments applied</small><b>{money(totals.back)}</b><span>Connected to your purchases</span></div><div><small>Friends still owe</small><b>{money(totals.owed)}</b><span>Only recorded agreements</span></div><div><small>You still owe</small><b>{money(totals.payable)}</b><span>Others paid on your behalf</span></div><div><small>Income identified</small><b>{money(totals.income)}</b><span>{money(totals.unresolved)} incoming unresolved</span></div></section>
 <div className="workbar"><div className="filters">{['All','Money in','Money out','Owed','Suggestions'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>{setFilter(f);}}>{f}</button>)}</div><div><label className="filed"><input type="checkbox" checked={showFiled} onChange={e=>setShowFiled(e.target.checked)}/> Show filed</label><button className="subtle" disabled={!routine.length} onClick={()=>{setChecked(routine.map(x=>x.id));setBatch(true);}}>Preview {routine.length} {routine.length===1?'suggestion':'suggestions'}</button></div></div>
 <main className={'workspace '+layout.toLowerCase()}><aside className="queue"><input className="search" aria-label="Search queue" placeholder="Find a record…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="queue-title"><span>{visible.length} visible records</span><span>CAD</span></div><div className="queue-scroll">{visible.map(x=><button key={x.id} aria-label={'Open '+x.name} className={'queue-item '+(selected===x.id?'chosen':'')} onClick={()=>open(x.id)}><span className={'direction '+(x.kind==='payable'?'violet':x.amount>0?'green':'')}>{linked(state,x.id)?'⇄':x.kind==='payable'?'○':x.amount>0?'↙':'↗'}</span><span><b>{x.name}</b><small>{x.account} · {x.event||x.date.slice(5)}</small></span><span className="queue-amount">{money(x.amount)}<small>{x.done?'Filed':linked(state,x.id)?'Linked':x.suggestedTag?'Suggested':used(x)?'Connected':'Open'}</small></span></button>)}{!visible.length&&<p className="empty">No records in this view. Change a filter or show filed items.</p>}</div></aside>
 <div className="focus-column"><div className="card-navigation"><button className="icon-button" aria-label="Previous card" disabled={visible.length<2} onClick={()=>open(visible[(Math.max(index,0)-1+visible.length)%visible.length].id)}>←</button><span>{index>=0?index+1:'—'} / {visible.length} <small>{r.done?'Filed · still editable':layout==='Focus'?'Focused record':'Selected record'}</small></span><button className="icon-button" aria-label="Next card" disabled={visible.length<2} onClick={()=>open(visible[(Math.max(index,0)+1)%visible.length].id)}>→</button></div>
 <article className="record-card" key={r.id}><div className="record-header"><div className="record-kicker"><Badge tone={payable?'violet':r.amount>0?'green':''}>{pair?'Linked transfer':payable?'Someone else paid':outgoing?'Money out':'Money in'}</Badge><span>{r.date.slice(5)} · CAD</span></div><div className="record-title"><div><h2>{r.name}</h2><p>{r.account}{r.person?' · '+r.person:''}</p></div><strong>{money(r.amount)}</strong></div>{r.event&&<button className="event-chip" onClick={()=>setPanel('Context')}>⌑ {r.event}</button>}</div><nav className="card-tools">{choices.map(p=><button key={p} className={p===active?'active':''} onClick={()=>setPanel(p)}>{p}</button>)}</nav><div className="editor" key={r.id+active}>{active==='Connections'?incomingConnections():active==='Income'?incomeEditor():active==='Tags'?tagEditor():active==='Shares'?sharesEditor():active==='Money back'||active==='Payments'?moneyBack():active==='Transfer'||active==='Connection'?transferEditor():contextEditor()}</div><footer className="card-footer"><div><b>{pair?'One movement · '+money(pair.fee)+' fee':payable?money(Math.max(0,(r.shares.Me||0)-recovered(state,r.id)))+' you still owe':expense?money(recovered(state,r.id))+' recovered · '+money(-r.amount-recovered(state,r.id))+' still fronted':money(allocationTotal)+' connected · '+money(r.income)+' income'}</b><small>Working copy updates immediately · Undo available</small></div><button className="primary" disabled={!ready(state,r)||r.done} onClick={file}>{r.done?'Filed':layout==='Focus'?'File & next':'File record'} <span>✓</span></button></footer></article><p className="focus-hint">Same records, same controls. Switch to {layout==='Focus'?'Desk for context across records':'Focus for one record at a time'}.</p></div>
 <aside className="context"><h3>People</h3>{['Alex','Maya'].map(p=>{const owes=state.rows.filter(x=>x.amount<0&&!linked(state,x.id)&&x.kind!=='settlement').reduce((n,x)=>n+Math.max(0,(x.shares[p]||0)-recovered(state,x.id,p)),0);const you=state.rows.filter(x=>x.kind==='payable'&&x.person===p).reduce((n,x)=>n+Math.max(0,(x.shares.Me||0)-recovered(state,x.id)),0);return <div className="person-context" key={p}><div><span className="avatar">{p[0]}</span><b>{p}</b></div><p>Owes you <b>{money(owes)}</b></p>{you>0&&<p>You owe <b>{money(you)}</b></p>}<div>{state.rows.filter(x=>x.person===p).map(x=><button key={x.id} onClick={()=>open(x.id)}>{x.name} ↗</button>)}</div></div>})}<h3>Events</h3>{eventNames.map(ev=><details key={ev} open><summary>{ev}<small>{state.rows.filter(x=>x.event===ev).length} records</small></summary>{state.rows.filter(x=>x.event===ev).map(x=><button className="event-record" key={x.id} onClick={()=>open(x.id)}><span>{x.name}</span><b>{money(Math.abs(x.amount))}</b></button>)}</details>)}<p className="micro">Payables are agreements, not imported account entries. This sample never nets what two people owe each other automatically.</p></aside></main>
 <div className="toast" role="status">{notice||'Your sample changes stay in this browser session. No app data is connected.'}</div>
 {batch&&<div className="scrim" onClick={e=>{if(e.target===e.currentTarget)setBatch(false);}}><section className="modal" role="dialog" aria-modal="true" aria-label="Batch suggestions" onKeyDown={e=>{if(e.key==='Escape')setBatch(false);}}><div className="section-line"><div><h2>Routine work, together.</h2><p>Inspect the proposed tags. Uncheck anything that needs individual attention.</p></div><button className="x" aria-label="Close suggestions" onClick={()=>setBatch(false)}>×</button></div><label className="select-all"><input type="checkbox" checked={checked.length===routine.length} onChange={e=>setChecked(e.target.checked?routine.map(r=>r.id):[])}/> Select all {routine.length} proposals</label><div className="batch-list">{routine.map(x=><label key={x.id}><input type="checkbox" checked={checked.includes(x.id)} onChange={e=>setChecked(c=>e.target.checked?[...c,x.id]:c.filter(id=>id!==x.id))}/><span><b>{x.name}</b><small>{x.date} · {x.account}</small></span><b>{money(x.amount)}</b><Badge>{x.suggestedTag}</Badge></label>)}</div><footer><span>Fixture suggestions · no live matching engine</span><button className="primary" disabled={!checked.length} onClick={()=>{change(s=>batchApply(s,checked),checked.length+' suggestions applied and filed. Undo restores the entire batch.');setBatch(false);}}>Apply {checked.length} & file</button></footer></section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
