import {seed} from './model.mjs';
export {money} from './model.mjs';
export const palette={Unallocated:'#d5d5d0',Gift:'#e5bdc8',Salary:'#bbcadf',Interest:'#bfcfca',Groceries:'#c0d2b7',Home:'#dfcbae',Dining:'#e6bfa5',Lodging:'#c9c1e2',Transfer:'#b8d5df',Fee:'#d9cdbb'};
export const total=r=>Math.abs(r.amount);
export const assigned=r=>r.layers.reduce((n,l)=>n+l.cents,0);
export const rest=r=>total(r)-assigned(r);
export const find=(s,id)=>s.find(r=>r.id===id);
export function initial(){return seed().rows.filter(r=>!['tickets','settle','departure'].includes(r.id)).map(r=>({...r,layers:[],saved:false})).concat([{id:'departure',name:'Savings transfer sent',amount:-50200,account:'Savings',date:'2026-08-13',layers:[],shares:{},saved:false}]);}
export function repayment(s,id,person,exclude){return s.filter(r=>r.id!==exclude&&(!person||r.person===person)).reduce((n,r)=>n+r.layers.filter(l=>l.kind==='expense'&&l.target===id).reduce((a,l)=>a+l.cents,0),0);}
export const paired=(s,id)=>s.find(r=>r.layers.some(l=>l.kind==='transfer'&&l.target===id));
export function cap(s,source,target){if(source.amount<=0||target.amount>=0||paired(s,target.id)||target.layers.some(l=>l.kind==='transfer'))return 0;const gross=total(target)-repayment(s,target.id,null,source.id);const share=Object.keys(target.shares||{}).length?(target.shares[source.person]||0)-repayment(s,target.id,source.person,source.id):gross;return Math.max(0,Math.min(share,gross));}
export function segments(s,r){const p=paired(s,r.id);if(p)return [{id:'principal',name:'Transfer to '+p.account,kind:'transfer',cents:p.amount,color:palette.Transfer},{id:'fee',name:'Transfer fee',kind:'fee',cents:total(r)-p.amount,color:palette.Fee}].filter(l=>l.cents);return [...r.layers.map(l=>({...l,color:palette[l.name]||palette[l.colorKey]||palette.Lodging})),{id:'other',name:'Unallocated',kind:'default',cents:rest(r),color:palette.Unallocated}].filter(l=>l.cents>0);}
function check(n){if(!Number.isSafeInteger(n)||n<0)throw Error('Use a nonnegative amount with at most two decimals.');}
export function resize(s,id,key,cents){check(cents);const r=find(s,id),l=r.layers.find(l=>l.id===key);if(!l||paired(s,id)||l.kind==='transfer')throw Error('Unlink the transfer before changing its amount.');if(cents>l.cents+rest(r))throw Error('Lower another layer first to make that amount available in Unallocated.');if(l.kind==='expense'&&cents>cap(s,r,find(s,l.target)))throw Error('That exceeds the remaining expense or the sender’s agreed share.');l.cents=cents;r.saved=false;return s;}
export function add(s,id,kind,target,cents){check(cents);const r=find(s,id);if(paired(s,id)||r.layers.some(l=>l.kind==='transfer'))throw Error('Unlink the transfer before adding a layer.');const key=kind+':'+target;if(r.layers.some(l=>l.id===key))throw Error('That layer is already present. Edit its amount instead.');if(cents>rest(r))throw Error('That exceeds the amount available in Unallocated.');if(kind==='expense'){const t=find(s,target);if(!t||cents>cap(s,r,t))throw Error('That exceeds the remaining expense or sender’s share.');r.layers.push({id:key,kind,target,name:t.name,colorKey:t.id==='cabin'?'Lodging':t.id==='dinner'?'Dining':'Groceries',cents});}else if(kind==='tag'){const allowed=r.amount>0?['Gift','Salary','Interest']:['Groceries','Home','Dining','Lodging'];if(!allowed.includes(target))throw Error('Choose a tag for this direction of money.');r.layers.push({id:key,kind,name:target,cents});}else if(kind==='transfer'){const t=find(s,target);if(!t||r.amount<=0||t.amount>=0||r.account===t.account||total(t)<total(r)||r.layers.length||t.layers.length||paired(s,t.id)||repayment(s,t.id))throw Error('Use an untouched outgoing record in another account that covers this receipt.');if(cents!==total(r))throw Error('This sample links whole incoming transfers.');r.layers.push({id:key,kind,target,name:'Transfer from '+t.account,cents,colorKey:'Transfer'});}else throw Error('Unsupported layer.');r.saved=false;return s;}
export function remove(s,id,key){const r=find(s,id);r.layers=r.layers.filter(l=>l.id!==key);r.saved=false;return s;}
export function boundary(s,id,index,delta){const r=find(s,id),parts=segments(s,r),a=parts[index],b=parts[index+1];if(!b||a.kind==='transfer'||b.kind==='transfer'||paired(s,id))return s;check(Math.abs(delta));let low=-a.cents,high=b.cents;if(a.kind==='expense')high=Math.min(high,cap(s,r,find(s,a.target))-a.cents);if(b.kind==='expense')low=Math.max(low,b.cents-cap(s,r,find(s,b.target)));const d=Math.max(low,Math.min(high,delta));r.layers.find(l=>l.id===a.id).cents+=d;if(b.id!=='other')r.layers.find(l=>l.id===b.id).cents-=d;r.saved=false;return s;}
export function pools(s){let recovered=0,internal=0,fees=0;const income={},expense={};for(const r of s){if(paired(s,r.id))continue;for(const l of segments(s,r)){if(l.kind==='expense')recovered+=l.cents;else if(l.kind==='transfer'){internal+=l.cents;fees+=total(find(s,l.target))-l.cents;}else{const dest=r.amount>0?income:expense;dest[l.name]=(dest[l.name]||0)+l.cents;}}}return {income,expense,recovered,internal,fees};}
