import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {initial,find,money,total,rest,segments,cap,add,resize,remove,boundary,palette,pools,repayment,paired} from './vial-model.mjs';
import './vial.css';
function Amount({label,value,commit}){const [text,setText]=useState((value/100).toFixed(2)),cancel=useRef(false);useEffect(()=>setText((value/100).toFixed(2)),[value]);return <label className="v-amount"><span>$</span><input aria-label={label} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onFocus={()=>{cancel.current=false;}} onBlur={()=>{if(!cancel.current)commit(/^\d+(\.\d{0,2})?$/.test(text)?Math.round(Number(text)*100):NaN);setText((value/100).toFixed(2));}} onKeyDown={e=>{if(e.key==='Escape'){cancel.current=true;e.target.blur();}if(e.key==='Enter')e.target.blur();}}/></label>}
function App(){const [state,setState]=useState(initial),[id,setId]=useState('alex'),[history,setHistory]=useState([]),[adding,setAdding]=useState(true),[query,setQuery]=useState(''),[kind,setKind]=useState('All'),[active,setActive]=useState(null),[notice,setNotice]=useState(''),[overview,setOverview]=useState(false),[step,setStep]=useState(100),[candidate,setCandidate]=useState(null),[amount,setAmount]=useState(0),[barAmount,setBarAmount]=useState(null),[hoverAmount,setHoverAmount]=useState(null);
const track=useRef(),searchInput=useRef(),drag=useRef(),r=find(state,id),parts=segments(state,r),source=paired(state,id),locked=!!source||r.layers.some(l=>l.kind==='transfer'),p=pools(state),received=repayment(state,id);
useEffect(()=>{if(!locked&&!r.layers.length){setAdding(true);setCandidate(null);}},[id,r.layers.length,locked]);
function change(fn,message){try{const next=structuredClone(state);fn(next);setHistory(h=>[...h.slice(-39),state]);setState(next);setNotice(message);return true;}catch(e){setNotice(e.message);return false;}}
function select(next){setBarAmount(null);setHoverAmount(null);setId(next);setAdding(false);setCandidate(null);setActive(null);setQuery('');setKind('All');}
function amountAt(y){const box=track.current.getBoundingClientRect();return Math.round(Math.max(0,Math.min(1,(box.bottom-y)/box.height))*total(r));}
function openFromBar(layer,e){if(locked)return;setBarAmount(e.detail===0?null:amountAt(e.clientY));setActive(layer);setAdding(true);setCandidate(null);setKind('All');setQuery('');searchInput.current?.focus({preventScroll:true});}
function moveAddCue(e){if(locked)return;setHoverAmount(amountAt(e.clientY));const box=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--add-y',Math.max(7,Math.min(93,(e.clientY-box.top)/box.height*100))+'%');}
function choose(c){setCandidate(c);setAmount(c.kind==='transfer'?total(r):Math.min(barAmount??rest(r),rest(r),c.max));}
function insert(){if(change(s=>add(s,id,candidate.kind,candidate.target,amount),'Layer added. The rest remains in Unallocated.')){setActive(candidate.kind+':'+candidate.target);setCandidate(null);setAdding(false);}}
let candidates=[];if(!locked){candidates=(r.amount>0?['Salary','Gift','Interest']:['Groceries','Home','Dining','Lodging']).map(name=>({kind:'tag',target:name,name,detail:r.amount>0?'Income tag':'Expense tag',color:palette[name],max:rest(r)}));if(r.amount>0){candidates.push(...state.filter(t=>t.id!==id&&cap(state,r,t)>0).map(t=>({kind:'expense',target:t.id,name:t.name,detail:`${t.event||t.account} · ${money(cap(state,r,t))} available`,color:palette[t.id==='cabin'?'Lodging':t.id==='dinner'?'Dining':'Groceries'],max:cap(state,r,t)})));if(!r.layers.length)candidates.push(...state.filter(t=>t.amount<0&&t.account!==r.account&&!t.layers.length&&!paired(state,t.id)&&!repayment(state,t.id)&&!Object.keys(t.shares||{}).length&&total(t)>=total(r)&&total(t)<=total(r)*1.1).map(t=>({kind:'transfer',target:t.id,name:t.name,detail:`${t.account} → ${r.account} · ${money(total(t)-total(r))} fee`,color:palette.Transfer,max:total(r)})));}candidates=candidates.filter(c=>!r.layers.some(l=>l.id===c.kind+':'+c.target)&&(kind==='All'||c.kind===kind)&&`${c.name} ${c.detail}`.toLowerCase().includes(query.toLowerCase()));}
const handlePoints=parts.slice(0,-1).map((l,i)=>parts.slice(0,i+1).reduce((n,x)=>n+x.cents,0)/total(r)*100);
const handleSlots=[...handlePoints];for(let i=1;i<handleSlots.length;i++)handleSlots[i]=Math.max(handleSlots[i],handleSlots[i-1]+8);if(handleSlots.length&&handleSlots.at(-1)>100){handleSlots[handleSlots.length-1]=100;for(let i=handleSlots.length-2;i>=0;i--)handleSlots[i]=Math.min(handleSlots[i],handleSlots[i+1]-8);}
const used=parts.filter(l=>l.kind!=='default').reduce((n,l)=>n+l.cents,0);
function dragStart(e,index){e.preventDefault();track.current.classList.add('dragging');e.currentTarget.setPointerCapture(e.pointerId);drag.current={index,y:e.clientY,base:structuredClone(state),moved:false};}
function dragMove(e){if(!drag.current)return;const d=drag.current;const delta=Math.round((e.clientY-d.y)/track.current.getBoundingClientRect().height*total(r)/step)*step;const next=structuredClone(d.base);boundary(next,id,d.index,delta);d.moved=true;setState(next);}
function dragEnd(){const completed=drag.current;drag.current=null;track.current?.classList.remove('dragging');if(completed?.moved)setHistory(h=>[...h.slice(-39),completed.base]);}
return <div className="v-app"><header className="v-header"><div className="v-brand"><b>u.</b><span>Urbanomics<small>Allocation study</small></span></div><span className="v-sample">Synthetic data · changes last until reload</span><div><button onClick={()=>setOverview(!overview)}>{overview?'Hide totals':'View totals'}</button><button aria-label="Undo" disabled={!history.length} onClick={()=>{setState(history.at(-1));setHistory(h=>h.slice(0,-1));setNotice('Last change undone.');}}>↶ Undo</button><button onClick={()=>change(s=>{s.splice(0,s.length,...initial());},'Sample reset. Undo restores your work.')}>Reset</button></div></header>
<div className="v-heading"><div><span className="v-eyebrow">ONE TRANSACTION. EVERY PORTION.</span><h1>A place for every dollar.</h1><p>Add a connection or a tag. The amount always stays whole.</p></div><a href="/?view=relationships">Earlier study ↗</a></div>
{overview&&<section className="v-pools"><div><h3>Income tags · all receipts</h3>{Object.entries(p.income).filter(([,n])=>n>0).map(([name,n])=><p key={name}><i style={{background:palette[name]}}/>{name}<b>{money(n)}</b></p>)}</div><div><h3>Expense tags · gross purchases</h3>{Object.entries(p.expense).filter(([,n])=>n>0).map(([name,n])=><p key={name}><i style={{background:palette[name]}}/>{name}<b>{money(n)}</b></p>)}</div><div><h3>Connections · separate from tags</h3><p>Recovered expenses<b>{money(p.recovered)}</b></p><p>Internal transfers<b>{money(p.internal)}</b></p><p>Transfer fees<b>{money(p.fees)}</b></p><small>Expense tags describe the original purchase. Recoveries reduce its remaining cost. Unlinked outgoings remain provisional.</small></div></section>}
<main className="v-workspace"><aside className="v-inbox"><h2>Transactions <span>{state.length}</span></h2>{state.map(row=>{const seg=segments(state,row);return <button key={row.id} className={'v-record '+(row.id===id?'selected':'')} onClick={()=>select(row.id)} aria-label={'Open '+row.name}><span><b>{row.name}</b><strong>{row.amount>0?'+':'−'}{money(total(row))}</strong></span><small>{row.account} · {row.date.slice(5)}{row.saved?' · Saved':''}</small><span className="v-mini" aria-label={'Breakdown for '+row.name}>{seg.filter(l=>l.cents>0).map(l=><i key={l.id} style={{width:l.cents/total(row)*100+'%',background:l.color}}/>)}</span></button>})}<p className="v-inbox-note">Every row has its own breakdown. Select one to work with its full amount.</p></aside>
<section className="v-sheet" aria-label="Selected transaction"><div className="v-receipt"><div><span className="v-eyebrow">{r.amount>0?'MONEY IN':'MONEY OUT'} · {r.date} </span><h2>{r.name}</h2><p>{r.account}{r.person?' · '+r.person:''}</p></div><div className="v-total"><strong>{money(total(r))}</strong><small>CAD · original amount</small></div></div>
<div className="v-body"><div className="v-vial-column"><div className="v-scale-top"><span>100%</span><b>{money(total(r))}</b></div><div className="v-vial-wrap"><div className={'v-vial '+(locked?'locked':'')} ref={track} onPointerMove={moveAddCue} onPointerEnter={moveAddCue} aria-label={'Allocation of '+money(total(r))+' for '+r.name}>{parts.map(l=><button key={l.id} className={'v-liquid '+(active===l.id?'highlight':'')} style={{height:l.cents/total(r)*100+'%',background:l.color}} aria-label={l.name+' '+money(l.cents)} disabled={locked} aria-describedby={!locked?'v-bar-add-help':undefined} onClick={e=>openFromBar(l.id,e)} title={locked?l.name+' · '+money(l.cents):undefined}>{l.cents/total(r)>.14&&<span>{l.name}<b>{money(l.cents)}</b></span>}</button>)}{!locked&&<span className="v-bar-add-cue" aria-hidden="true"><span>＋</span><b>Add layer<small>{hoverAmount===null?'':((hoverAmount/total(r)*100).toFixed(1).replace(/\.0$/,'')+'% · '+money(hoverAmount))}</small></b></span>}</div>{!locked&&<span className="v-sr-only" id="v-bar-add-help">Click or press Enter to add a layer to this transaction.</span>}{!locked&&<svg className="v-leaders" viewBox="0 0 32 100" preserveAspectRatio="none" aria-hidden="true">{handlePoints.map((pos,i)=><line key={i} x1="0" y1={pos} x2="27" y2={handleSlots[i]}/>)}</svg>}{!locked&&parts.slice(0,-1).map((l,i)=>{const pos=parts.slice(0,i+1).reduce((n,x)=>n+x.cents,0)/total(r)*100;return <button key={l.id} className="v-divider" style={{top:handleSlots[i]+'%'}} role="slider" aria-label={'Boundary after '+l.name} aria-valuemin={0} aria-valuemax={l.cents+parts[i+1].cents} aria-valuenow={l.cents} aria-valuetext={money(l.cents)} onPointerDown={e=>dragStart(e,i)} onPointerMove={dragMove} onPointerUp={dragEnd} onLostPointerCapture={dragEnd} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();change(s=>boundary(s,id,i,(e.key==='ArrowDown'?1:-1)*step),'Boundary adjusted.');}}}>≡</button>})}</div><div className="v-scale-bottom"><span>0%</span><span>{parts.filter(l=>l.cents>0).length} layers</span></div><div className="v-precision"><span>Adjust by</span>{[100,1].map(n=><button className={step===n?'chosen':''} key={n} onClick={()=>setStep(n)}>{n===100?'$1':'1¢'}</button>)}</div></div>
<div className="v-layer-space"><div className="v-section-title"><span>Breakdown</span><button className={'v-add '+(adding?'open':'')} disabled={locked} aria-expanded={adding} onClick={()=>{setAdding(!adding);setCandidate(null);setBarAmount(null);}}>＋ Add layer <span>→</span></button></div><div className="v-layers">{parts.map(l=><div key={l.id} className={'v-layer '+(active===l.id?'active':'')+(l.kind==='default'?' default':'')} style={{'--tint':l.color}}><i/><div className="v-layer-label"><b>{l.name}</b><small>{l.kind==='expense'?'Deducts from this expense':l.kind==='tag'?(r.amount>0?'Income tag':'Expense tag'):l.kind==='transfer'?'Internal account movement':l.kind==='fee'?'External transfer cost':'Not yet allocated'}</small></div>{l.kind==='default'||locked?<strong>{money(l.cents)}</strong>:<Amount label={'Amount for '+l.name} value={l.cents} commit={n=>change(s=>resize(s,id,l.id,n),'Layer amount updated.')}/ >}{l.kind!=='default'&&!source&&<button className="v-remove" aria-label={'Remove '+l.name} onClick={()=>change(s=>remove(s,id,l.id),'Layer removed; its amount returns to Unallocated.')}>×</button>}</div>)}</div>
{adding?<section className="v-picker"><div className="v-picker-heading"><b>{candidate?'Set the amount':'Add to this transaction'}</b><button aria-label="Close add layer" onClick={()=>{setAdding(false);setCandidate(null);}}>×</button></div>{candidate?<><button className="v-back" onClick={()=>setCandidate(null)}>← All options</button><div className="v-choice"><i style={{background:candidate.color}}/><div><b>{candidate.name}</b><small>{candidate.detail}</small></div></div>{barAmount!==null&&<p className="v-click-amount">{candidate.kind==='transfer'?'Transfers link the whole incoming amount.':'Bar selection: '+money(barAmount)+(barAmount>Math.min(rest(r),candidate.max)?' · limited to '+money(Math.min(rest(r),candidate.max))+' available.':'.')}</p>}<div className="v-add-amount"><Amount label="New layer amount" value={amount} commit={n=>{if(Number.isSafeInteger(n)&&n>=0)setAmount(n);else setNotice('Enter an amount with up to two decimals.');}}/><button onClick={()=>setAmount(Math.min(rest(r),candidate.max))}>Use available</button><small>{money(rest(r))} in Unallocated</small></div><button className="v-primary" onClick={insert}>{candidate.kind==='transfer'?'Link transfer & accept fee':'Add layer'}</button></>:<><div className="v-kind-tabs">{[['All','All'],['tag','Tags'],...(r.amount>0?[['expense','Expenses'],['transfer','Transfers']]:[])].map(([value,label])=><button key={value} className={kind===value?'selected':''} onClick={()=>setKind(value)}>{label}</button>)}</div><input className="v-search" ref={searchInput} autoFocus aria-label="Find a tag or connection" placeholder="Find a tag or connection…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="v-options">{candidates.map(c=><button key={c.kind+c.target} onClick={()=>choose(c)}><i style={{background:c.color}}/><span><b>{c.name}</b><small>{c.detail}</small></span><em>{c.kind==='tag'?'Tag':c.kind==='expense'?'Expense':'Transfer'}</em><strong>＋</strong></button>)}{!candidates.length&&<p>No matching options. Try another filter.</p>}</div></>}</section>:<div className="v-layer-hint">{source?<><b>Connected to {source.name}</b><button onClick={()=>select(source.id)}>Open the incoming side →</button></>:locked?<><b>This amount is an internal transfer.</b><p>Removing the connection returns it to Unallocated and restores the outgoing record.</p></>:<><span>↗</span><p>{r.layers.length?'Adjust an amount, drag a boundary, or add another layer.':'Start with a tag or an expense connection. Each layer takes its amount from Unallocated.'}</p></>}</div>}
{r.amount<0&&received>0&&<div className="v-recovery"><b>{money(received)} repaid · {money(total(r)-received)} still fronted</b><p>Your tag layers still describe the original {money(total(r))} purchase.</p>{state.filter(x=>x.layers.some(l=>l.kind==='expense'&&l.target===id)).map(x=><button key={x.id} onClick={()=>select(x.id)}>{x.name} ↗</button>)}</div>}
</div></div><footer className="v-footer"><div><b>{money(used)} specifically assigned <span>·</span> {money(parts.find(l=>l.id==='other')?.cents||0)} Unallocated</b><small>{r.event?'Event: '+r.event+' · ':''}Each layer belongs to this transaction.</small></div><button className="v-primary" onClick={()=>change(s=>{find(s,id).saved=true;},'Allocation saved in this sample. Unallocated stays unassigned.')}>{r.saved?'Saved ✓':'Keep allocation'}</button></footer></section></main><div role="status" className="v-toast">{notice||'This is a disposable sample. Your real transactions are untouched.'}</div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
