const fs=require('node:fs'),path=require('node:path'),{createHash,randomUUID}=require('node:crypto');
// Child-first order respects every financial/configuration foreign key.
const tables=['transaction_rule_applications','review_items','observations','staged_paths','jobs','imports','transactions','cash_receipts','snapshots','rules','transaction_rules','transaction_aliases','review_entity_history','review_entities','transfer_lab_config','category_palettes','system_tag_names','account_import_layouts','accounts','source_layouts','import_layouts','sources','settings'];
function safeFolder(root,name){const folder=path.resolve(root,name),relative=path.relative(root,folder);if(relative.startsWith('..')||path.isAbsolute(relative))throw Error('Reset path is outside the workspace.');fs.mkdirSync(folder,{recursive:true});const resolved=fs.realpathSync(folder),base=fs.realpathSync(root);if(!resolved.startsWith(base+path.sep))throw Error('Reset cannot follow a folder outside the workspace.');return folder;}
function intake(store){return ['dropbox','inbox'].flatMap(folder=>{const directory=safeFolder(store.root,folder);return fs.readdirSync(directory,{withFileTypes:true}).map(entry=>{if(!entry.isFile())throw Error('Move non-file items out of '+folder+' before resetting.');const file=path.join(directory,entry.name);return {folder,name:entry.name,hash:createHash('sha256').update(fs.readFileSync(file)).digest('hex')};});});}
function previewReset(store){const existing=store.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(r=>r.name);if(existing.some(t=>!tables.includes(t)))throw Error('This workspace has data the reset command does not recognize.');const hash=createHash('sha256').update('start-from-scratch-v1'),counts={};for(const table of tables){const rows=store.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all();counts[table]=rows.length;hash.update(JSON.stringify([table,rows]));}const files=intake(store);hash.update(JSON.stringify(files));return {counts,intake:files.length,token:hash.digest('hex')};}
function resetWorkspace(store,token,confirmation){if(confirmation!=='RESET')throw Error('Type RESET to confirm starting from scratch.');const preview=previewReset(store);if(token!==preview.token)throw Error('Workspace changed. Preview the reset again.');store.recover();if(store.archiveError)throw Error('Finish archive recovery before resetting: '+store.archiveError);const current=previewReset(store);if(current.token!==token)throw Error('Archive recovery changed the workspace. Preview the reset again.');const archive=safeFolder(store.root,'archive/workspace-resets'),backup=path.join(archive,randomUUID());fs.mkdirSync(backup,{recursive:true});store.db.prepare('VACUUM INTO ?').run(path.join(backup,'workspace.sqlite'));const files=intake(store),moved=[];fs.writeFileSync(path.join(backup,'manifest.json'),JSON.stringify({action:'start-from-scratch',created:store.now().toISOString(),counts:current.counts,intake:files,archives:'Original sources and snapshot files remain at archive/sources and archive/snapshots.'},null,2),{flag:'wx'});
try{store.review.atomic(()=>{if(previewReset(store).token!==token)throw Error('Workspace changed. Preview the reset again.');for(const entry of files){const from=path.resolve(store.root,entry.folder,entry.name),to=path.resolve(backup,entry.folder,entry.name);if(!from.startsWith(path.resolve(store.root,entry.folder)+path.sep)||!to.startsWith(backup+path.sep))throw Error('Invalid intake path.');fs.mkdirSync(path.dirname(to),{recursive:true});fs.renameSync(from,to);moved.push({from,to});}for(const table of tables)store.db.exec('DELETE FROM '+table);store.db.prepare("INSERT INTO settings(key,value) VALUES('workspaceReset',?)").run(JSON.stringify({created:store.now().toISOString(),backup}));});}catch(error){for(const {from,to}of moved.reverse())fs.renameSync(to,from);throw error;}
store.archiveError=null;return {counts:current.counts,backup,intake:files.length};}
module.exports={previewReset,resetWorkspace,tables};
