import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import '@derekurban/design-system/styles.css';
import './icons.js';
import {Icon} from '@derekurban/design-system';
import './style.css';
import {scenarios, people, events, tags, money, plain, person, event, partView, gapOf} from './scenarios.mjs';
import {ink, parts, total, signed, Describe, Strip, Amount, Chip, GapChip, Dot, RuleBlock, SplitRows, Meta, Status, EventChip, Candidates, RowHead} from './shared.jsx';
import {R2} from './round2.jsx';
import {R3} from './round3.jsx';
import {R4} from './round4.jsx';
import * as M4 from './model4.mjs';

/* ---------- the ten variations ---------- */
const V = {};
V[1] = {title: 'Baseline', note: 'What ships today: strip, part chips, split panel, note, next-time card, side meta.', render: s => <div className="editor v1"><div className="main"><Describe s={s} /><Strip s={s} height={44} amounts handles /><div className="chips">{parts(s).map((p, i) => <Chip key={i} p={p} onRemove />)}<GapChip s={s} /><EventChip s={s} /></div><SplitRows s={s} /><Candidates s={s} /><RuleBlock s={s} /></div><div className="side"><Meta s={s} /><small>Each change saves right away. Undo is in the corner.</small></div></div>};

V[2] = {title: 'Ledger line', note: 'Minimal height. One row of pills under the box; everything else behind Details. For speed through a month.', render: s => <Line s={s} />};
function Line({s}) { const [more, setMore] = useState(false); return <div className="editor v2"><Describe s={s} compact /><div className="line"><Strip s={s} height={10} labels={false} /><div className="pills">{parts(s).map((p, i) => <Chip key={i} p={p} onRemove />)}<GapChip s={s} /><EventChip s={s} />{s.shares && <span className="chip is-people"><Icon name="users" size={14} /><b>{s.shares.people.map(p => person(p.id).name).join(', ')}</b></span>}</div><Status s={s} /><button className="link" onClick={() => setMore(v => !v)}>{more ? 'Less' : 'Details'}</button></div>{more && <div className="line-more"><SplitRows s={s} dense /><Candidates s={s} /><RuleBlock s={s} layout="line" /><Meta s={s} inline /></div>}</div>; }

V[3] = {title: 'Money and context', note: 'Two columns: what the money did on the left, who and what it belongs to on the right. Each context item is a row with its own action.', render: s => <div className="editor v3"><Describe s={s} /><div className="cols"><section><h4>Amount</h4><Strip s={s} height={36} amounts handles /><table className="partlist"><tbody>{parts(s).map((p, i) => <tr key={i}><td><Dot color={p.color} />{p.name}</td><td className="num"><Amount cents={p.cents} label={p.name} /></td><td><button className="icon" aria-label="Remove"><Icon name="x" size={14} /></button></td></tr>)}{gapOf(s) > 0 && <tr className="gap"><td>Unsorted</td><td className="num">{plain(gapOf(s))}</td><td /></tr>}</tbody></table><Candidates s={s} /></section><section><h4>Context</h4><div className="ctx"><Icon name="calendar-days" size={16} /><span><b>Event</b><small>{s.event ? event(s.event).name : 'None'}</small></span><button className="link">{s.event ? 'Change' : 'Add'}</button></div><div className="ctx"><Icon name="users" size={16} /><span><b>Split</b><small>{s.shares ? `${s.shares.people.map(p => `${person(p.id).name} ${money(p.cents)}`).join(' · ')} · me ${money(s.shares.me)}` : s.kind === 'expense' ? 'Just you' : s.person ? `From ${person(s.person).name}` : 'None'}</small></span><button className="link">{s.shares ? 'Edit' : 'Share'}</button></div><div className="ctx"><Icon name="repeat" size={16} /><span><b>Rule</b><small>{s.rule.state === 'none' ? `None for ${s.name}` : s.rule.state === 'exists' ? s.rule.name : `Suggested by ${s.rule.name}`}</small></span><button className="link">{s.rule.state === 'none' ? 'Remember' : s.rule.state === 'suggested' ? 'Confirm' : 'Review'}</button></div><div className="ctx"><Icon name="file-text" size={16} /><span><b>Source</b><small>{s.original} · {s.account.name} · {s.date}</small></span><button className="link">Open</button></div></section></div></div>};

V[4] = {title: 'Receipt', note: 'A narrow column that reads like a till receipt: lines, a subtotal, then split, event and rule as footers.', render: s => <div className="editor v4"><Describe s={s} /><div className="receipt"><div className="r-head"><b>{s.name}</b><span>{signed(s)}</span></div>{parts(s).map((p, i) => <div key={i} className="r-line"><Dot color={p.color} /><span>{p.name}</span><Amount cents={p.cents} label={p.name} /></div>)}{gapOf(s) > 0 && <div className="r-line is-gap"><i className="dot gapdot" /><span>Unsorted</span><span className="num">{plain(gapOf(s))}</span></div>}<div className="r-rule" /><div className="r-line is-total"><span>Total</span><span className="num">{plain(total(s))}</span></div>{s.shares && <><div className="r-rule" /><div className="r-cap">Split {s.shares.source === 'event' ? `· follows ${event(s.event).name}` : '· custom'}</div>{s.shares.people.map(p => <div key={p.id} className="r-line"><Dot color={person(p.id).color} /><span>{person(p.id).name}{p.repaid ? <small> repaid {money(p.repaid)}</small> : null}</span><Amount cents={p.cents} label={person(p.id).name} /></div>)}<div className="r-line"><i className="dot" style={{background: 'var(--data-neutral)'}} /><span>Me</span><span className="num">{plain(s.shares.me)}</span></div></>}<Candidates s={s} /><div className="r-rule" />{s.event && <div className="r-foot"><Icon name="calendar-days" size={14} />{event(s.event).name}<button className="link">Change</button></div>}<div className="r-foot"><Icon name="file-text" size={14} />{s.original} · {s.date}<button className="link">Original file ↗</button></div><RuleBlock s={s} layout="receipt" /></div></div>};

V[5] = {title: 'Facts', note: 'Four facts with a done or open mark: tags, split, event, rule. Each expands in place. Shows at a glance what still needs you.', render: s => <Facts s={s} />};
function Facts({s}) {
  const [open, setOpen] = useState('tags');
  const g = gapOf(s), ps = parts(s);
  const rows = [
    {id: 'tags', done: !g && !s.suggested, title: s.kind === 'transfer' ? 'Internal transfer' : 'Tags', text: ps.length ? ps.map(p => `${p.name} ${money(p.cents)}`).join(' · ') + (g ? ` · ${money(g)} unsorted` : '') : 'Nothing yet', action: g ? 'Add' : 'Edit', body: <><Strip s={s} height={36} amounts handles /><div className="chips">{ps.map((p, i) => <Chip key={i} p={p} onRemove />)}<GapChip s={s} /></div><Candidates s={s} /></>},
    ...(s.kind === 'expense' ? [{id: 'split', done: !!s.shares, title: 'Split', text: s.shares ? `${s.shares.people.map(p => `${person(p.id).name} ${money(p.cents)}`).join(' · ')} · me ${money(s.shares.me)}` : 'Just you', action: s.shares ? 'Edit' : 'Share', body: <SplitRows s={s} dense />}] : []),
    {id: 'event', done: !!s.event, title: 'Event', text: s.event ? event(s.event).name : 'None', action: s.event ? 'Change' : 'Add', body: <div className="chips">{events.map(e => <span key={e.id} className={'chip is-event' + (s.event === e.id ? ' is-on' : '')} style={{'--c': e.color}}><Icon name="calendar-days" size={14} /><b>{e.name}</b></span>)}</div>},
    {id: 'rule', done: s.rule.state === 'exists', title: 'Rule', text: s.rule.state === 'none' ? `None for ${s.name}` : s.rule.state === 'exists' ? s.rule.name : `Suggested by ${s.rule.name} · confirm`, action: s.rule.state === 'none' ? 'Remember' : s.rule.state === 'suggested' ? 'Confirm' : 'Review', body: <RuleBlock s={s} layout="facts" />},
  ];
  return <div className="editor v5"><Describe s={s} />{rows.map(r => <div key={r.id} className={'fact' + (open === r.id ? ' is-open' : '')}><button className="fact-head" onClick={() => setOpen(open === r.id ? '' : r.id)}><Icon name={r.done ? 'circle-check' : 'circle-dashed'} size={16} /><b>{r.title}</b><span>{r.text}</span><em>{r.action}</em></button>{open === r.id && <div className="fact-body">{r.body}</div>}</div>)}<Meta s={s} inline /></div>;
}

V[6] = {title: 'Proportional chips', note: 'No separate strip. The chips are the bar: each one is as wide as its share, with the boundary between them draggable.', render: s => { const ps = parts(s), g = gapOf(s); return <div className="editor v6"><Describe s={s} /><div className="prop">{ps.map((p, i) => <div key={i} className="prop-chip" style={{flexGrow: p.cents, background: p.color, color: ink(p.color)}}><b>{p.name}</b><span>{plain(p.cents)}</span></div>)}{g > 0 && <div className="prop-chip is-gap" style={{flexGrow: g}}><b>Unsorted</b><span>{plain(g)}</span></div>}</div><div className="prop-row"><div className="avatars">{s.shares ? s.shares.people.map(p => <span key={p.id} className="avatar" style={{background: person(p.id).color}} title={`${person(p.id).name} ${money(p.cents)}`}>{person(p.id).name[0]}</span>) : s.person ? <span className="avatar" style={{background: person(s.person).color}}>{person(s.person).name[0]}</span> : <span className="avatar is-empty">+</span>}<small>{s.shares ? `Split ${s.shares.people.length + 1} ways · me ${money(s.shares.me)}` : s.person ? `From ${person(s.person).name}` : 'Just you'}</small></div><EventChip s={s} />{!s.event && <span className="chip is-ghost"><Icon name="calendar-days" size={14} /><b>Event</b></span>}<span className={'chip is-rule' + (s.rule.state !== 'none' ? ' is-on' : '')}><Icon name="repeat" size={14} /><b>{s.rule.state === 'none' ? 'Remember' : s.rule.state === 'exists' ? 'Rule on' : 'Suggested'}</b></span><Status s={s} /></div><Candidates s={s} /><Meta s={s} inline /></div>; }};

V[7] = {title: 'Form', note: 'Labeled fields in a grid. Predictable and scannable; nothing moves. For people who like forms.', render: s => <div className="editor v7"><Describe s={s} /><div className="form"><label><span>Tags</span><div className="chips">{parts(s).filter(p => p.kind === 'tag').map((p, i) => <Chip key={i} p={p} onRemove />)}<button className="ghost"><Icon name="plus" size={14} /> Tag</button></div></label><label><span>Connections</span><div className="chips">{parts(s).filter(p => p.kind !== 'tag').map((p, i) => <Chip key={i} p={p} onRemove />)}<GapChip s={s} />{s.kind === 'income' && <button className="ghost"><Icon name="plus" size={14} /> Repayment</button>}</div></label><label><span>Split with</span><div className="chips">{people.map(p => <span key={p.id} className={'chip is-person' + (s.shares?.people.some(x => x.id === p.id) ? ' is-on' : '')} style={{'--c': p.color}}><i /><b>{p.name}</b>{s.shares?.people.find(x => x.id === p.id) && <Amount cents={s.shares.people.find(x => x.id === p.id).cents} label={p.name} />}</span>)}{s.shares && <small>me {money(s.shares.me)}</small>}</div></label><label><span>Event</span><select defaultValue={s.event || ''}><option value="">None</option>{events.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label><span>Next time</span><RuleBlock s={s} layout="form" /></label><label><span>Source</span><Meta s={s} inline /></label></div></div>};

V[8] = {title: 'Focus header', note: 'The strip becomes the card header, full width, with the parts listed as rows beneath and three tiles for people, event and rule.', render: s => <div className="editor v8"><div className="band"><Strip s={s} height={56} amounts /><div className="band-amount">{signed(s)}</div></div><Describe s={s} /><div className="tiles"><div className="tile"><small><Icon name="users" size={14} /> Split</small><b>{s.shares ? `${s.shares.people.length + 1} ways` : s.person ? person(s.person).name : 'Just you'}</b><span>{s.shares ? `me ${money(s.shares.me)} · ${s.shares.people.filter(p => p.repaid < p.cents).length} still owe` : s.kind === 'expense' ? 'Share it' : s.person ? 'Repaying' : ''}</span></div><div className="tile"><small><Icon name="calendar-days" size={14} /> Event</small><b>{s.event ? event(s.event).name : 'None'}</b><span>{s.event ? `${event(s.event).start} to ${event(s.event).end}` : 'Add context'}</span></div><div className="tile"><small><Icon name="repeat" size={14} /> Rule</small><b>{s.rule.state === 'none' ? 'None' : s.rule.state === 'exists' ? 'On' : 'Suggested'}</b><span>{s.rule.state === 'none' ? 'Remember these settings' : s.rule.name}</span></div></div><table className="partlist"><tbody>{parts(s).map((p, i) => <tr key={i}><td><Dot color={p.color} />{p.name}<small>{p.sub}</small></td><td className="num"><Amount cents={p.cents} label={p.name} /></td><td><button className="icon" aria-label="Remove"><Icon name="x" size={14} /></button></td></tr>)}{gapOf(s) > 0 && <tr className="gap"><td>Unsorted</td><td className="num">{plain(gapOf(s))}</td><td /></tr>}</tbody></table><Candidates s={s} /></div>};

V[9] = {title: 'Inspector', note: 'The row does not expand. A docked panel on the right holds the card with tabs, so the list stays readable while you work.', render: s => <Inspector s={s} />};
function Inspector({s}) {
  const [tab, setTab] = useState('amount');
  const tabs = [['amount', 'Amount'], ...(s.kind === 'expense' ? [['people', 'Split']] : s.kind === 'income' ? [['people', 'From']] : []), ['rule', 'Rule'], ['source', 'Source']];
  return <aside className="inspector"><header><div><b>{s.name}</b><small>{s.account.name} · {s.date}</small></div><strong className={s.amount > 0 ? 'is-in' : ''}>{signed(s)}</strong><button className="icon" aria-label="Close"><Icon name="x" size={16} /></button></header><Describe s={s} /><nav className="tabs">{tabs.map(([id, label]) => <button key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === 'amount' && <><Strip s={s} height={36} amounts handles /><div className="chips">{parts(s).map((p, i) => <Chip key={i} p={p} onRemove />)}<GapChip s={s} /><EventChip s={s} /></div><Candidates s={s} /></>}
    {tab === 'people' && (s.shares ? <SplitRows s={s} dense /> : <p className="hint">{s.kind === 'income' ? `From ${person(s.person).name}` : 'Not shared. Type a name in the box to split it.'}</p>)}
    {tab === 'rule' && <RuleBlock s={s} layout="inspector" />}
    {tab === 'source' && <Meta s={s} />}
    <footer><Status s={s} /><small>Saved</small></footer></aside>;
}

V[10] = {title: 'Console', note: 'Text first. The box is the only control; the facts are sentences with key hints. For keyboard-driven sorting.', render: s => { const ps = parts(s), g = gapOf(s); const line = (k, text, done) => <div className={'con-line' + (done ? '' : ' is-open')}><kbd>{k}</kbd><span>{text}</span></div>; return <div className="editor v10"><Describe s={s} /><div className="console">{line('t', ps.length ? `tagged ${ps.map(p => `${p.name.toLowerCase()} ${plain(p.cents)}`).join(', ')}${g ? ` · ${plain(g)} unsorted` : ''}` : `nothing tagged · ${plain(g)} unsorted`, !g)}{s.kind === 'expense' && line('s', s.shares ? `split with ${s.shares.people.map(p => `${person(p.id).name.toLowerCase()} ${plain(p.cents)}`).join(', ')} · me ${plain(s.shares.me)}${s.shares.source === 'event' ? ` · follows ${event(s.event).name.toLowerCase()}` : ''}` : 'not shared', !!s.shares)}{s.kind === 'income' && s.person && line('p', `from ${person(s.person).name.toLowerCase()}`, true)}{line('e', s.event ? `in ${event(s.event).name.toLowerCase()}` : 'no event', !!s.event)}{line('r', s.rule.state === 'none' ? `no rule · press r to remember for "${s.rule.pattern.replace('^', '').toLowerCase()}"` : s.rule.state === 'exists' ? `rule on · ${s.rule.name.toLowerCase()}` : `suggested by ${s.rule.name.toLowerCase()} · press r to confirm`, s.rule.state === 'exists')}{line('o', `${s.original.toLowerCase()} · ${s.account.name.toLowerCase()} · ${s.date}`, true)}</div><div className="con-foot"><kbd>↑</kbd><kbd>↓</kbd> next row · <kbd>z</kbd> undo · <kbd>esc</kbd> close</div></div>; }};

/* ---------- page ---------- */
/* Opening a row morphs name, amount and strip between their closed and open places. */
function transition(fn) {
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (document.startViewTransition && !reduced) document.startViewTransition(() => { fn(); return new Promise(r => setTimeout(r, 0)); });
  else fn();
}
function App() {
  const q = new URLSearchParams(location.search);
  const [round, setRound] = useState(() => Number(q.get('round')) || 4);
  const [rows4, setRows4] = useState(M4.initialRows); const [history4, setHistory4] = useState([]);
  const act4 = fn => transition(() => setRows4(prev => { const next = fn(prev); if (next !== prev) setHistory4(h => [...h.slice(-29), prev]); return next; }));
  const undo4 = () => transition(() => setHistory4(h => { const prev = h.at(-1); if (prev) setRows4(prev); return h.slice(0, -1); }));
  const [v, setV] = useState(() => Number(q.get('v')) || 1);
  const [sid, setSid] = useState(() => q.get('s') || 'split');
  const [openId, setOpenId] = useState(() => q.get('s') || (Number(q.get('round') || 4) === 4 ? 'cabin' : 'split'));
  const [theme, setTheme] = useState('light');
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { history.replaceState(null, '', `?round=${round}&v=${v}&s=${round === 2 ? openId || sid : sid}`); }, [round, v, sid, openId]);
  const set = round === 4 ? R4 : round === 3 ? R3 : round === 2 ? R2 : V, current = set[v] || set[1], vv = set[v] ? v : 1;
  const s = scenarios.find(x => x.id === sid), neighbours = scenarios.filter(x => x.id !== sid).slice(0, 2);
  const toggle = id => transition(() => setOpenId(open => open === id ? null : id));
  const openScenario = openId && scenarios.find(x => x.id === openId);
  const intro = round === 4 ? 'Three playable approaches to the four natures: Move, Spend, Receive, Offset. Same ledger in all three; tags take amounts, settlements draw down what a person owes, moves pair entries, events apply splits, rules get remembered. Undo and Reset at the right.' : round === 3 ? 'Five takes on Halves and Strip-is-the-editor. The header line is the card header, the strip is the tag editor, event, people and rule each have their own place, and the source sits behind the info mark.' : round === 2 ? 'Six layouts where the closed row is the open card header. Click any row: its name, amount and strip move into place instead of appearing twice.' : 'Ten ways to lay out an opened row in Organize. The describe box stays; everything under it varies.';
  return <div className="page">
    <header className="top"><div><p className="crumb">Study</p><h1>Open card</h1><p>{intro} Synthetic data, nothing saves.</p></div>
      <div className="tools"><div className="segc" role="group" aria-label="Round"><button aria-pressed={round === 1} onClick={() => { setRound(1); setV(1); }}>Round 1</button><button aria-pressed={round === 2} onClick={() => { setRound(2); setV(1); }}>Round 2</button><button aria-pressed={round === 3} onClick={() => { setRound(3); setV(1); }}>Round 3</button><button aria-pressed={round === 4} onClick={() => { setRound(4); setV(1); }}>Round 4</button></div>{round === 4 && <div className="segc" role="group" aria-label="Ledger"><button disabled={!history4.length} onClick={undo4}><Icon name="undo-2" size={14} /> Undo</button><button onClick={() => transition(() => { setRows4(M4.initialRows()); setHistory4([]); })}>Reset</button></div>}<div className="segc" role="group" aria-label="Theme"><button aria-pressed={theme === 'light'} onClick={() => setTheme('light')}><Icon name="sun" size={16} /></button><button aria-pressed={theme === 'dark'} onClick={() => setTheme('dark')}><Icon name="moon" size={16} /></button></div></div></header>
    <div className="pickers"><div className="chips" role="group" aria-label="Variation">{Object.keys(set).map(k => <button key={k} className="pick" aria-pressed={Number(k) === vv} onClick={() => transition(() => setV(Number(k)))}>{k} · {set[k].title}</button>)}</div>{round === 1 && <div className="chips" role="group" aria-label="Scenario">{scenarios.map(x => <button key={x.id} className="pick" aria-pressed={x.id === sid} onClick={() => setSid(x.id)}>{x.label}</button>)}</div>}</div>
    <p className="note"><b>{vv} · {current.title}.</b> {current.note}</p>
    {round === 1 ? <div className={'frame' + (vv === 9 ? ' has-inspector' : '')}>
      <ol className="ledger"><li className="row"><RowHead s={neighbours[0]} /></li><li className={'row is-open' + (vv === 9 ? ' is-selected' : '')}><RowHead s={s} />{vv !== 9 && current.render(s)}</li><li className="row"><RowHead s={neighbours[1]} /></li></ol>
      {vv === 9 && current.render(s)}
    </div> : round === 4 ? <div className={'frame' + (current.Balances ? ' has-balances' : '')}>
      <ol className="ledger">{rows4.map(x => <current.Row key={x.id} rows={rows4} row={x} act={act4} open={openId === x.id} onToggle={() => toggle(x.id)} />)}</ol>
      {current.Balances && <current.Balances rows={rows4} />}
    </div> : <div className={'frame' + (current.Panel && openScenario ? ' has-inspector' : '')}>
      <ol className="ledger">{scenarios.map(x => <current.Row key={x.id} s={x} open={openId === x.id} onToggle={() => toggle(x.id)} />)}</ol>
      {current.Panel && openScenario && <current.Panel s={openScenario} onClose={() => toggle(openScenario.id)} />}
    </div>}
    <div className="toast"><Icon name="check" size={16} /><span>Tagged Lodging</span><button><Icon name="undo-2" size={14} /> Undo</button></div>
  </div>;
}
createRoot(document.getElementById('root')).render(<App />);
