const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {ImportStore}=require('../../electron/imports/store.cjs');
const {csv}=require('../../electron/imports/parsers.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'urbanomics-allocations-')),store=new ImportStore(root);t.after(()=>store.close());const account=store.addAccount('Sample','pc','chequing');const file=path.join(root,'sample.csv');fs.writeFileSync(file,csv([['Description','Type','Card Holder Name','Date','Time','Amount'],...[["Expense",-300],["Receipt",275],["Empty",20]].map(([name,n])=>[name,'SAMPLE','SAMPLE','09/01/2026','12:00 AM',n])]));store.resolveAccount(store.enqueue([file]).ids[0],account,false);const row=name=>store.review.records().find(r=>r.description===name);const save=(name,draft)=>{const r=row(name);store.review.allocation(r.id,r.version,draft);};return {store,row,save};}
test('empty and partial allocations persist without Other, and mixed receipts conserve reporting',async t=>{const {store,row,save}=fixture(t);const tag=store.review.entity('category',{name:'Gift',flowType:'income',color:'#aaaaaa'}),food=store.review.entity('category',{name:'Food',color:'#aaaaaa'}),person=store.review.entity('person',{name:'Alex',color:'#aaaaaa'});
save('Empty',{tags:[]});assert.deepEqual(store.review.state().records.find(r=>r.id===row('Empty').id).review.tags,[]);assert.equal(row('Empty').review.allocationMode,'layers');
save('Expense',{tags:[{id:food,cents:10000}]});store.review.financial(row('Expense').id,row('Expense').version,{kind:'expense',reviewed:true,shares:[{id:'me',cents:3000},{id:person,cents:27000}],personId:'',allocations:[],remainder:0,transferId:''});save('Receipt',{tags:[{id:tag,cents:500}],allocations:[{id:row('Expense').id,cents:27000}],personId:person});
const {dashboard}=await import('../../src/dashboard-model.js'),state=store.review.state(),d=dashboard(state.records,state.entities,{from:'2026-09-01',through:'2026-09-30',currency:'CAD'});assert.equal(d.cashIn,29500);assert.equal(d.cashOut,30000);assert.equal(d.incomeReceived,500);assert.equal(d.repaymentReceived,27000);assert.equal(d.otherReceived,2000);assert.equal(d.net,3000);
const {mapRecords,segments}=await import('../../src/allocation-model.js');let rows=mapRecords(state.records,state.entities),r=rows.find(r=>r.id===row('Receipt').id);assert.equal(segments(rows,r).length,2);assert.equal(segments(rows,r).some(l=>l.kind==='default'),false);
save('Receipt',{tags:[{id:tag,cents:27500}]});rows=mapRecords(store.review.state().records,state.entities);r=rows.find(r=>r.id===row('Receipt').id);assert.equal(segments(rows,r).length,1);
const version=row('Empty').version;save('Empty',{tags:[]});assert.throws(()=>store.review.allocation(row('Empty').id,version,{tags:[]}),/changed|version|stale/i);
});
test('invalid portions and repayment identities reject atomically; rules preserve partial allocations',t=>{const {store,row,save}=fixture(t);const tag=store.review.entity('category',{name:'Food',color:'#aaaaaa'}),income=store.review.entity('category',{name:'Income',flowType:'income',color:'#aaaaaa'});const before=JSON.stringify(store.review.records());for(const draft of [{tags:[{id:tag,cents:30001}]},{tags:[{id:income,cents:100}]},{tags:[{id:'system:other:expense',cents:10}]}])assert.throws(()=>save('Expense',draft));assert.throws(()=>save('Receipt',{allocations:[{id:row('Expense').id,cents:100}]}));assert.equal(JSON.stringify(store.review.records()),before);save('Expense',{tags:[{id:tag,cents:100}]});store.transactionRules.save({name:'Rule',pattern:'^Expense',categoryId:tag,personId:'',direction:'out',enabled:true});const p=store.transactionRules.state();store.transactionRules.apply(p.token);assert.deepEqual(row('Expense').review.tags,[{id:tag,cents:100}]);});

test('event links save atomically with allocation changes and invalid events roll back',t=>{const {store,row,save}=fixture(t);const event=store.review.entity('group',{name:'Weekend',color:'#aaaaaa',startDate:'2026-09-01',endDate:'2026-09-03'}),tag=store.review.entity('category',{name:'Groceries',color:'#aaaaaa'});save('Expense',{tags:[{id:tag,cents:100}],groups:[event]});assert.deepEqual(row('Expense').review.groups,[event]);const before=JSON.stringify(store.review.records());assert.throws(()=>save('Expense',{tags:[],groups:['missing-event']}),/Group/);assert.equal(JSON.stringify(store.review.records()),before);save('Expense',{tags:[],groups:[]});assert.deepEqual(row('Expense').review.groups,[]);});
