const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ImportStore}=require('../../electron/imports/store.cjs');const {createWorkspaceService}=require('../../electron/workspace-service.cjs');const {configurationSQL}=require('../../electron/configuration.cjs');const {customParse}=require('../../electron/imports/layouts.cjs');
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'urbanomics-v2-')),store=new ImportStore(root),service=createWorkspaceService({store,platform:{}});t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true})});return {store,service,file:(name,text)=>{const file=path.join(root,name);fs.writeFileSync(file,text);return file}};}
const text='Posted,Memo,Value\n2026-07-31,Synthetic coffee,-12.34\n2026-08-01,Synthetic pay,300.00\n';
const values={name:'Custom signed export',prefixRegex:'.*',headers:['Posted','Memo','Value'],mapping:{date:0,description:1,amount:2,balance:null,dateFormat:'ymd',amountMode:'signed',sign:1,currency:'CAD',delimiter:','}};
test('V2 has no preset bank layouts and gates import until every file is mapped and assigned',async t=>{
 const {store,service,file}=setup(t);
 const paths=[file('one.csv','Transfer date,Description,Amount,Balance\n2026-08-01,Synthetic one,10.00,10.00\n'),file('two.csv','Date,Transaction Details,Funds Out,Funds In\n08/01/2026,Synthetic two,5.00,\n')];
 const staged=(await service.invoke('imports:stage',paths)).value;
 assert.equal(store.layouts.list().length,0);
 for(const id of staged.ids){assert.equal(store.layouts.inspect(id).schema,null);assert.equal(store.job(id).status,'error');}
 assert.equal((await service.invoke('imports:process',staged.ids)).ok,false);
 const first=store.layouts.save(staged.ids[0],{...values,name:'Main layout',prefixRegex:'^one.*',headers:['Transfer date','Description','Amount','Balance'],mapping:{...values.mapping,balance:3}});
 const a=store.addAccount('Main','custom:'+first.id,'',{prefixRegex:'^one.*'});
 assert.equal((await service.invoke('imports:process',staged.ids)).ok,false);
 assert.equal(store.review.records().length,0);
 const second=store.layouts.save(staged.ids[1],{...values,name:'Travel layout',prefixRegex:'^two.*',headers:['Date','Transaction Details','Funds Out','Funds In'],mapping:{...values.mapping,amountMode:'separate',debit:2,credit:3,dateFormat:'mdy'}});
 const b=store.addAccount('Travel','custom:'+second.id,'My holiday fund');await service.invoke('imports:assign',staged.ids[1],b);
 const result=await service.invoke('imports:process',staged.ids);assert.equal(result.ok,true,result.error);assert.equal(result.value.added,2);
 assert.equal(store.state().accounts.find(x=>x.id===a).kind,'');store.updateAccount(b,{name:'Trip',kind:'',prefixRegex:'',color:'#123456'});assert.equal(store.state().accounts.find(x=>x.id===b).kind,'');
});
test('custom layouts preview all rows, preserve source interpretation, dedupe and route future exports',async t=>{const {store,service,file}=setup(t);const original=file('custom_july.csv',text),id=(await service.invoke('imports:stage',[original])).value.ids[0];assert.equal(store.layouts.inspect(id).headers[0],'Posted');assert.equal(store.layouts.preview(id,values).rowCount,2);const template=store.layouts.save(id,values);const a=store.addAccount('Everyday','custom:'+template.id,'',{prefixRegex:'^custom_.*'});assert.equal(store.job(id).account_id,a);assert.equal(store.state().months.length,0);assert.equal((await service.invoke('imports:process',[id])).value.added,2);const archived=fs.readFileSync(path.join(store.root,'archive/sources',store.job(id).source_hash+'.csv'));assert.equal(archived.toString(),text);const again=store.enqueue([original],{stage:true,process:false}).ids[0];const repeat=await service.invoke('imports:process',[again]);assert.equal(repeat.value.added,0);assert.equal(repeat.value.matched,2);assert.throws(()=>store.layouts.apply(again,template.id),/pending|imported/);const fresh=store.enqueue([file('custom_august.csv',text+'2026-08-02,Synthetic tea,-1.25\n')],{stage:true,process:false}).ids[0];assert.equal(store.job(fresh).account_id,a);assert.equal((await service.invoke('imports:process',[fresh])).value.added,1);const sql=configurationSQL(store.db);assert.match(sql,/INSERT INTO "import_layouts"/);assert.ok(!sql.includes('Synthetic coffee'));assert.ok(!sql.includes('source_layouts'));assert.throws(()=>store.layouts.remove(template.id,template.version),/used/);assert.equal(store.db.prepare('PRAGMA foreign_key_check').all().length,0);});
test('bad mapped row rejects entire file and invalid edits do not replace binding',t=>{const {store,file}=setup(t);const id=store.enqueue([file('bad.csv',text+'2026-02-30,Impossible date,10\n')],{stage:true,process:false}).ids[0];assert.throws(()=>store.layouts.save(id,values),/Record 4: Invalid/);assert.equal(store.layouts.list().length,0);assert.equal(store.state().months.length,0);const good=store.enqueue([file('good.csv',text)],{stage:true,process:false}).ids[0];const saved=store.layouts.save(good,values);const edited=store.layouts.save(good,{...values,name:'Renamed template',id:saved.id,version:saved.version});assert.equal(edited.version,2);assert.throws(()=>store.layouts.save(good,{...values,id:saved.id,version:1}),/changed/);assert.equal(store.layouts.inspect(good).preview[0].amountCents,-1234);});
test('explicit date order, polarity, currency and separate columns use exact cents',()=>{const template={id:'sample',name:'Separate',headers:['When','What','Out','In'],mapping:{date:0,description:1,debit:2,credit:3,dateFormat:'dmy',amountMode:'separate',sign:1,currency:'USD',delimiter:';'}};const p=customParse(Buffer.from('When;What;Out;In\n03/04/2026;Coffee;0.01;\n'),template);assert.equal(p.rows[0].date,'2026-04-03');assert.equal(p.rows[0].amountCents,-1);assert.equal(p.rows[0].currency,'USD');assert.throws(()=>customParse(Buffer.from('When;What;Out;In\n03/04/2026;Coffee;1;2\n'),template),/one side/);assert.throws(()=>customParse(Buffer.from('When;What;Out;In\n03/04/2026;Coffee;;\n'),template),/Missing amount/);assert.throws(()=>customParse(Buffer.from('When;What;Out;In\n03/04/2026;Coffee;1.001;\n'),template),/valid dollars/);});
test('regex feedback distinguishes literal, pattern and unmatched portions using actual RE2 match',t=>{const {store}=setup(t);assert.deepEqual(store.testPrefix('^PC_.*','PC_Aug.csv').segments,[{text:'PC_',kind:'literal'},{text:'Aug.csv',kind:'pattern'}]);assert.equal(store.testPrefix('^PC_','PC_Aug.csv').segments.at(-1).kind,'unmatched');assert.equal(store.testPrefix('^EQ.*','PC.csv').matches,false);assert.throws(()=>store.testPrefix('[','PC.csv'),/Invalid prefix/);assert.equal(store.testPrefix('^PC_|^EQ_','EQ_aug.csv').literalEnd,0);});
test('V2 can explicitly teach a second layout for an existing account without mixing identities',async t=>{const {store,service,file}=setup(t);const account=store.addAccount('One account','eq','',{prefixRegex:'^same_.*'});const id=store.enqueue([file('same_custom.csv',text)],{stage:true,process:false}).ids[0];const template=store.layouts.save(id,values);assert.equal(store.job(id).account_id,null);const assigned=await service.invoke('imports:assign',id,account);assert.equal(assigned.ok,true,assigned.error);assert.equal((await service.invoke('imports:process',[id])).value.added,2);const next=store.enqueue([file('same_later.csv',text+'2026-08-03,Synthetic lunch,-9.01\n')],{stage:true,process:false}).ids[0];assert.equal(store.job(next).account_id,account);assert.equal((await service.invoke('imports:process',[next])).value.added,1);assert.equal(store.state().accounts.length,1);assert.match(configurationSQL(store.db),/INSERT INTO "account_import_layouts"/);});
test('template edits preserve pinned source mappings and require disambiguation for overlapping definitions',async t=>{const {store,service,file}=setup(t);const first=store.enqueue([file('first.csv',text)],{stage:true,process:false}).ids[0],saved=store.layouts.save(first,values),account=store.addAccount('Account','custom:'+saved.id);store.resolveAccount(first,account,false,{process:false});await service.invoke('imports:process',[first]);const next=store.enqueue([file('second.csv',text+'2026-08-05,Synthetic expense,-6\n')],{stage:true,process:false}).ids[0];store.layouts.save(next,{...values,id:saved.id,version:1,mapping:{...values.mapping,sign:-1}});assert.equal(store.layouts.inspect(first).preview[0].amountCents,-1234);assert.equal(store.layouts.inspect(next).preview[0].amountCents,1234);const alt=store.enqueue([file('third.csv',text+'2026-08-06,Synthetic expense,-7\n')],{stage:true,process:false}).ids[0];store.layouts.save(alt,{...values,name:'Alternate'});const ambiguous=store.enqueue([file('fourth.csv',text+'2026-08-07,Synthetic expense,-8\n')],{stage:true,process:false}).ids[0];assert.equal(store.job(ambiguous).status,'error');assert.match(store.job(ambiguous).error,/Multiple layouts/);store.layouts.apply(ambiguous,saved.id);assert.equal(store.layouts.inspect(ambiguous).preview[0].amountCents,1234);});
test('semicolon templates auto-recognize new exports and native originals keep their original parser',async t=>{const {store,service,file}=setup(t);const semitext='When;Memo;Value\n2026-08-01;Coffee, breakfast;-5\n',v={...values,prefixRegex:'^semi.*',headers:['When','Memo','Value'],mapping:{...values.mapping,delimiter:';'}};const id=store.enqueue([file('semi.csv',semitext)],{stage:true,process:false}).ids[0];const template=store.layouts.save(id,v),account=store.addAccount('Semi','custom:'+template.id,'',{prefixRegex:'^semi.*'});const next=store.enqueue([file('semi-next.csv',semitext+'2026-08-02;Tea;-1\n')],{stage:true,process:false}).ids[0];assert.equal(store.job(next).status,'queued');assert.equal((await service.invoke('imports:process',[next])).value.added,2);
const native='Transfer date,Description,Amount,Balance\n2026-08-03,Original,10,10\n',nativeFile=file('eq.csv',native),original=store.enqueue([nativeFile],{stage:true,process:false,manualLayouts:false}).ids[0],eq=store.addAccount('EQ','eq');store.resolveAccount(original,eq);const modified=store.enqueue([file('eq-new.csv',native+'2026-08-04,Next,11,21\n')],{stage:true,process:false}).ids[0];store.layouts.save(modified,{name:'Custom EQ convention',headers:['Transfer date','Description','Amount','Balance'],mapping:{...values.mapping,balance:3,sign:-1}});assert.equal(store.layouts.inspect(original).preview[0].amountCents,1000);assert.equal(store.layouts.inspect(modified).preview[0].amountCents,-1000);});
test('an unused template can be removed without deleting the staged original',t=>{const {store,file}=setup(t),id=store.enqueue([file('unused.csv',text)],{stage:true,process:false}).ids[0],template=store.layouts.save(id,values),hash=store.job(id).source_hash;store.layouts.remove(template.id,template.version);assert.equal(store.layouts.list().length,0);assert.equal(store.job(id).status,'error');assert.match(store.job(id).error,/Choose a layout/);assert.equal(fs.readFileSync(path.join(store.root,'archive/sources',hash+'.csv'),'utf8'),text);assert.equal(store.db.prepare('PRAGMA foreign_key_check').all().length,0);});

test('layout filename rules are independent, header-only matches do not route, and conflicts fail closed',async t=>{
 const {store,service,file}=setup(t);const stage=async(name,body=text)=>(await service.invoke('imports:stage',[file(name,body)])).value.ids[0];
 const id=await stage('Personal_Jul.csv');const layout=store.layouts.save(id,{...values,prefixRegex:'^Personal_.*'});
 const a=store.addAccount('Everyday','custom:'+layout.id,'',{prefixRegex:'^Personal_.*'});
 const next=await stage('Personal_Aug.csv',text+'2026-08-08,Next,-5\n');assert.equal(store.job(next).account_id,a);
 const unmatched=await stage('Different.csv',text+'2026-08-09,Another,-6\n');assert.equal(store.layouts.inspect(unmatched).schema,null);
 const wrong=await stage('Personal_Wrong.csv','Other,Columns\n1,2\n');assert.match(store.job(wrong).error,/Headers do not match/);
 assert.throws(()=>store.layouts.save(unmatched,{...values,prefixRegex:'['}),/Invalid prefix regex/);
 const manual=store.layouts.save(unmatched,{...values,name:'Manual',prefixRegex:''});
 const later=await stage('Unmatched.csv',text+'2026-08-10,Later,-7\n');assert.equal(store.layouts.inspect(later).schema,null);
 assert.equal(store.layouts.list().find(t=>t.id===manual.id).prefixRegex,'');
 assert.match(configurationSQL(store.db),/prefixRegex/);
});
test('V2 Dropbox scan also requires mapping for built-in bank headers',async t=>{
 const {store,service}=setup(t);fs.writeFileSync(path.join(store.root,'dropbox','bank.csv'),'Transfer date,Description,Amount,Balance\n2026-08-01,Sample,10,10\n');
 const result=await service.invoke('workspace:scan',true);assert.equal(result.ok,true);assert.equal(store.layouts.inspect(result.value.ids[0]).schema,null);
});

test('schema 21 releases unused built-in mappings but preserves imported originals and configuration',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'urbanomics-layout-migration-'));let store=new ImportStore(root);t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true})});
 const file=(name,text)=>{const p=path.join(root,name);fs.writeFileSync(p,text);return p};
 const body='Transfer date,Description,Amount,Balance\n2026-08-01,Original,10,10\n';
 const original=store.enqueue([file('old.csv',body)],{process:false}).ids[0],account=store.addAccount('Existing','eq');store.resolveAccount(original,account);
 const pending=store.enqueue([file('pending.csv',body+'2026-08-02,Pending,5,15\n')],{process:false}).ids[0];
 const records=store.review.records();store.db.exec('ALTER TABLE import_layouts DROP COLUMN prefixRegex; PRAGMA user_version=20');store.close();store=new ImportStore(root);
 assert.deepEqual(store.review.records(),records);assert.equal(store.layouts.inspect(original).preview[0].amountCents,1000);
 assert.equal(store.layouts.inspect(pending).schema,null);assert.equal(store.job(pending).account_id,null);
 assert.equal(fs.readFileSync(path.join(root,'archive/sources',store.job(original).source_hash+'.csv'),'utf8'),body);
 const saved=store.layouts.save(pending,{...values,name:'My layout',prefixRegex:'^pending.*',headers:['Transfer date','Description','Amount','Balance'],mapping:{...values.mapping,balance:3}});
 const otherRoot=fs.mkdtempSync(path.join(os.tmpdir(),'urbanomics-layout-config-')),other=new ImportStore(otherRoot);
 try{other.db.exec(configurationSQL(store.db));assert.equal(other.layouts.get(saved.id).prefixRegex,'^pending.*');assert.equal(other.review.records().length,0);}finally{other.close();fs.rmSync(otherRoot,{recursive:true,force:true})}
});
