const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {ImportStore}=require('../../electron/imports/store.cjs'),{csv}=require('../../electron/imports/parsers.cjs'),{configurationSQL,seedConfiguration}=require('../../electron/configuration.cjs'),{needsTagging}=require('../../electron/review/system-tags.mjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'urbanomics-templates-')),store=new ImportStore(root);t.after(()=>store.close());const account=store.addAccount('Sample','pc','chequing'),a=store.review.entity('category',{name:'Food',color:'#aaaabb'}),b=store.review.entity('category',{name:'Home',color:'#bbbbcc'}),person=store.review.entity('person',{name:'Alex',color:'#aaaabb'});let seq=0;function add(name,amount=-10.01){const file=path.join(root,'batch'+seq+++'.csv');fs.writeFileSync(file,csv([['Description','Type','Card Holder Name','Date','Time','Amount'],[name,'SAMPLE','SAMPLE','09/01/2026','12:00 AM',amount]]));const ids=store.enqueue([file]).ids;for(const id of ids)if(['routing','overlap','error','queued'].includes(store.job(id).status))store.resolveAccount(id,account,false);return store.review.records().find(r=>r.description===name);}const rule={name:'Template',pattern:'^Shop',direction:'out',categoryId:'',personId:person,enabled:true,template:{tags:[{id:a,weight:6000},{id:b,weight:3000}],groups:[],autoReview:false}};return {root,store,add,a,b,person,rule};}
test('template imports exact proportions, keeps pending review, preserves manual edits and archives',async t=>{const {store,add,rule,person}=fixture(t);const id=store.transactionRules.save(rule),row=add('Shop first');assert.deepEqual(row.review.tags.map(p=>p.cents),[601,300]);assert.equal(row.review.assignedPersonId,person);assert.equal(row.review.templateReview,'pending');assert.ok(needsTagging(row));const version=row.version;add('Shop first');assert.equal(store.review.records().find(r=>r.id===row.id).version,version);const source=JSON.stringify(store.db.prepare('SELECT * FROM transactions').all());store.review.allocation(row.id,row.version,{tags:row.review.tags});assert.equal(store.review.records().find(r=>r.id===row.id).review.templateReview,undefined);assert.equal(JSON.stringify(store.db.prepare('SELECT * FROM transactions').all()),source);const state=store.transactionRules.state();store.transactionRules.apply(state.token);assert.equal(store.review.records().find(r=>r.id===row.id).review.templateReview,undefined);assert.throws(()=>store.review.removeEntity(rule.template.tags[0].id),/template/);assert.throws(()=>store.review.removeEntity(person),/rule/);
const saved=store.transactionRules.rules().find(r=>r.id===id);store.transactionRules.save({...saved,template:{...saved.template,autoReview:true}});const next=add('Shop automatic');assert.equal(next.review.templateReview,'accepted');assert.equal(needsTagging(next),false);const {attentionQueues}=await import('../../src/experimental-model.js');assert.equal(attentionQueues(store.review.state().records,{routes:[],maxDays:1,basisPoints:0}).expenses.some(r=>r.id===next.id),false);
store.admin.untagAll(store.admin.preview().token);assert.equal(store.review.records().find(r=>r.id===next.id).review.templateReview,undefined);});
test('templates conflict with other matches and validate before writes; preview and configuration stay separate from ledger',t=>{const {store,root,add,rule,a}=fixture(t);const initial=add('Shop existing'),before=JSON.stringify(store.review.records());const id=store.transactionRules.save(rule);assert.equal(JSON.stringify(store.review.records()),before);assert.equal(store.transactionRules.preview({...rule,id,version:1}).matches[0].status,'ready');store.transactionRules.save({name:'Competing',pattern:'^Shop',direction:'out',categoryId:a,personId:'',enabled:true});const row=add('Shop conflict');assert.deepEqual(row.review.tags,[]);assert.equal(store.transactionRules.state().candidates.find(c=>c.id===row.id).status,'conflict');assert.throws(()=>store.transactionRules.save({...rule,name:'Invalid',template:{...rule.template,tags:[{id:a,weight:10001}]}}),/percentages/);
const config=configurationSQL(store.db),file=path.join(root,'config.sql');fs.writeFileSync(file,config);assert.ok(!config.includes(initial.id));const fresh=new ImportStore(path.join(root,'fresh'));try{seedConfiguration(fresh.db,file);assert.deepEqual(fresh.transactionRules.rules().find(r=>r.id===id).template,rule.template);assert.equal(fresh.review.records().length,0);}finally{fresh.close();}});

test('income templates preserve event context and auto-review controls the income queue',async t=>{const {store,add,person}=fixture(t),tag=store.review.entity('category',{name:'Salary',flowType:'income',color:'#aaaabb'}),event=store.review.entity('group',{name:'Sample event',color:'#aaaabb',startDate:'2026-09-01',endDate:'2026-09-02'});const rule={name:'Income template',pattern:'^Salary',direction:'in',categoryId:'',personId:person,enabled:true,template:{tags:[{id:tag,weight:10000}],groups:[event],autoReview:false}},id=store.transactionRules.save(rule);const pending=add('Salary pending',123.45),{attentionQueues}=await import('../../src/experimental-model.js');const queued=()=>attentionQueues(store.review.state().records,{routes:[],maxDays:1,basisPoints:0}).income;assert.equal(pending.review.tags[0].cents,12345);assert.deepEqual(pending.review.groups,[event]);assert.ok(queued().some(r=>r.id===pending.id));assert.throws(()=>store.review.removeEntity(event),/template/);const saved=store.transactionRules.rules().find(r=>r.id===id);store.transactionRules.save({...saved,template:{...saved.template,autoReview:true}});const accepted=add('Salary accepted',99.99);assert.ok(!queued().some(r=>r.id===accepted.id));assert.ok(queued().some(r=>r.id===pending.id));});

test('template capture scales small transactions into exact percentage points',async()=>{const {templateWeights}=await import('../../src/allocation-model.js');assert.deepEqual(templateWeights(1797,[{id:'food',cents:1000},{id:'home',cents:797}]),[{id:'food',weight:5565},{id:'home',weight:4435}]);assert.deepEqual(templateWeights(1,[{id:'food',cents:1}]),[{id:'food',weight:10000}]);assert.deepEqual(templateWeights(1797,[]),[]);assert.deepEqual(templateWeights(100000,[{id:'food',cents:60000}]),[{id:'food',weight:6000}]);assert.throws(()=>templateWeights(1,[{id:'food',cents:2}]),/fit/);});

test('coverage discovers ordinary and disabled rules and explains overlaps without changing records',t=>{const {store,add,rule,a,person}=fixture(t);const row=add('Shop coverage'),before=JSON.stringify(store.review.records());const ordinary=store.transactionRules.save({name:'Ordinary groceries',pattern:'^Shop',categoryId:a,direction:'out',enabled:true});const disabled=store.transactionRules.save({...rule,name:'Disabled template',enabled:false});const coverage=store.transactionRules.coverage(row.id);assert.deepEqual(new Set(coverage.rules.map(r=>r.id)),new Set([ordinary,disabled]));assert.equal(coverage.rules.find(r=>r.id===disabled).enabled,false);assert.equal(coverage.decision.status,'ready');const preview=store.transactionRules.preview({...rule,name:'Proposed reuse'}),match=preview.matches.find(r=>r.id===row.id);assert.equal(match.status,'conflict');assert.equal(match.ruleDetails.find(r=>r.id===ordinary).categoryId,a);assert.equal(match.ruleDetails.find(r=>r.id==='draft').personId,person);assert.equal(match.ruleDetails.find(r=>r.id==='draft').template.tags[0].weight,6000);assert.equal(JSON.stringify(store.review.records()),before);});

test('template enable rechecks newly competing rules after a preview',t=>{const {store,add,rule,a}=fixture(t);add('Shop preview');assert.equal(store.transactionRules.preview(rule).matches[0].status,'ready');store.transactionRules.save({name:'New competitor',pattern:'^Shop',categoryId:a,direction:'out',enabled:true});assert.throws(()=>store.transactionRules.save(rule),/New competitor/);assert.equal(store.transactionRules.rules().length,1);store.transactionRules.save({...rule,enabled:false});assert.equal(store.transactionRules.rules().length,2);});
