import React, {useEffect,useMemo,useState} from "react";
import {AccountEditor,AccountDeleteDialog} from "./AccountSettings.jsx";
import {WorkspaceModal} from "./WorkspaceModal.jsx";
import {InfoDot,money,monthLabel} from "./snapshots-v2-atoms.jsx";
import {accountsModel} from "./accounts-model.js";
import "./accounts-workspace.css";
import { Icon } from "@derekurban/design-system";
const api=window.urbanomics;
const shortMonth=m=>new Date(m+"-15T12:00:00Z").toLocaleDateString("en-CA",{month:"short",timeZone:"UTC"});
const initials=name=>name.split(/\s+/).slice(0,2).map(n=>n[0]).join("");

export function AccountsWorkspace({data,busy,run,onSnapshots,onSource}){
  const [source,setSource]=useState(null),[layouts,setLayouts]=useState([]),[error,setError]=useState(""),[reload,setReload]=useState(0);
  const [selected,setSelected]=useState(""),[currencyChoice,setCurrency]=useState(""),[yearChoice,setYear]=useState(""),[month,setMonth]=useState("");
  const [editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[observations,setObservations]=useState(false),[limit,setLimit]=useState(10);
  useEffect(()=>{let live=true;Promise.all([api.reviewState(),api.importLayouts()]).then(([s,l])=>{if(live){setSource(s);setLayouts(l);setError("");}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[data,reload]);
  const records=source?.records||[];
  const activeIds=new Set(data.accounts.map(a=>a.id));
  const liveRows=records.filter(r=>!r.deleted&&!r.manual&&activeIds.has(r.accountId));
  const currencies=[...new Set(liveRows.map(r=>r.currency))].sort();
  const currency=currencies.includes(currencyChoice)?currencyChoice:currencies.includes("CAD")?"CAD":currencies[0]||"CAD";
  const years=[...new Set(liveRows.filter(r=>r.currency===currency).map(r=>r.date.slice(0,4)))].sort().reverse();
  const year=years.includes(yearChoice)?yearChoice:years[0]||String(new Date().getFullYear());
  const models=useMemo(()=>accountsModel(records,data.accounts,{year,currency}),[source,data.accounts,year,currency]);
  const account=models.find(a=>a.id===selected)||models[0];
  const selectedMonth=account?.months.find(m=>m.month===month&&m.count)?month:"";
  const period=selectedMonth?account.months.find(m=>m.month===selectedMonth):account;
  const recent=account?.rows.filter(r=>selectedMonth?r.date.startsWith(selectedMonth):r.date.startsWith(year))||[];
  const routes=(account?.routes||[]).map(r=>({...r,pairs:r.pairs.filter(p=>!selectedMonth||p.row.date.startsWith(selectedMonth))})).filter(r=>r.pairs.length);
  const max=Math.max(1,...(account?.months||[]).flatMap(m=>[m.cashIn,m.cashOut]));
  const periodLabel=selectedMonth?monthLabel(selectedMonth):year;
  const reset=()=>{setMonth("");setLimit(10);setObservations(false);};
  return <div className="accounts-workspace">
    <div className="accounts-heading"><div><h1>Accounts</h1></div><div className="accounts-actions"><button onClick={onSnapshots}>Import CSVs</button><button className="primary" disabled={busy||!source} onClick={()=>setEditing({})}>+ Add account</button></div></div>
    {error&&<div role="alert" className="accounts-notice">{error} <button onClick={()=>setReload(n=>n+1)}>Retry</button></div>}
    {!source&&!error&&<p role="status">Loading accounts…</p>}
    {source&&!data.accounts.length&&<div className="accounts-empty"><span aria-hidden="true"><Icon name="wallet" size={24}/></span><h2>A place for every account.</h2><p>Add an account using a saved CSV layout, or start with an export in Snapshots.</p><button onClick={onSnapshots}>Start with a CSV →</button></div>}
    {!!data.accounts.length&&source&&<>
      <div className="accounts-toolbar"><span>{data.accounts.length} accounts</span><div><label className="accounts-select-label">Currency<select aria-label="Account currency" value={currency} onChange={e=>{setCurrency(e.target.value);reset();}}>{(currencies.length?currencies:[currency]).map(c=><option key={c}>{c}</option>)}</select></label></div></div>
      <div className="accounts-cards" role="group" aria-label="Choose account">{models.map(a=><button className="accounts-tile" key={a.id} style={{"--account-color":a.color}} aria-pressed={a.id===account.id} onClick={()=>{setSelected(a.id);reset();}}><span className="accounts-tile-top"><span className="accounts-monogram">{initials(a.name)}</span><span><strong>{a.name}</strong><small>{a.kind||"Account"}</small></span><span className="accounts-selection" aria-hidden="true">{a.id===account.id?<Icon name="check" size={14}/>:""}</span></span><span className="accounts-balance">{a.balance.value!==null?money(a.balance.value,currency):"—"}</span><small>{a.balance.ambiguous?"Multiple balance observations":a.balance.date?`Reported · ${a.balance.date}`:"No reported balance"}</small><span className="accounts-tile-bottom"><span>{a.rows.length.toLocaleString()} transactions</span><span>{currency}</span></span></button>)}</div>
      {account&&<div className="accounts-detail" key={account.id} style={{"--account-color":account.color}}>
        <div className="accounts-detail-heading"><div><span className="accounts-dot"/><h2>{account.name}</h2></div><button disabled={busy} aria-label={`Edit ${account.name}`} onClick={()=>setEditing(account)}>Edit account</button></div>
        <div className="accounts-columns"><div className="accounts-main-column">
          <section className="accounts-panel accounts-flow" aria-label="Account cash flow"><div className="accounts-panel-heading"><h3>Money movement <InfoDot label="Account cash flow">Money entering or leaving your accounts. Matched internal transfers are excluded, except for fees or excess received. This includes repayments and is not net spending. Select a month to inspect it; select it again to see the year.</InfoDot></h3><label className="accounts-select-label">Year<select aria-label="Account year" value={year} disabled={!years.length} onChange={e=>{setYear(e.target.value);reset();}}>{(years.length?years:[year]).map(y=><option key={y}>{y}</option>)}</select></label></div>
            <div className="accounts-chart-legend"><span><i className="accounts-in-key"/>Money in</span><span><i className="accounts-out-key"/>Money out</span><small>{currency} · monthly totals</small></div>
            <div className="accounts-chart" role="group" aria-label="Monthly money movement">{account.months.map(m=><button key={m.month} disabled={!m.count} className="accounts-month" aria-pressed={selectedMonth===m.month} aria-label={`${monthLabel(m.month)}: money in ${money(m.cashIn,currency)}, money out ${money(m.cashOut,currency)}${m.count?"":", no transactions"}`} title={m.count?`${monthLabel(m.month)} · In ${money(m.cashIn,currency)} · Out ${money(m.cashOut,currency)}`:"No imported transactions"} onClick={()=>{setMonth(selectedMonth===m.month?"":m.month);setLimit(10);}}><span className="accounts-bar-pair"><i className="accounts-bar-in" style={{height:100*m.cashIn/max+"%"}}/><i className="accounts-bar-out" style={{height:100*m.cashOut/max+"%"}}/></span><span>{shortMonth(m.month)}</span><i className={m.count?"accounts-month-dot filled":"accounts-month-dot"}/></button>)}</div>
            <div className="accounts-period"><span>{periodLabel}</span>{selectedMonth&&<button onClick={()=>{setMonth("");setLimit(10);}}>Whole year</button>}</div>
            <div className="accounts-metrics"><div><small>Money in</small><strong data-testid="account-money-in">{money(period.cashIn,currency)}</strong></div><div><small>Money out</small><strong data-testid="account-money-out">{money(period.cashOut,currency)}</strong></div><div><small>Net external flow</small><strong>{money(period.cashIn-period.cashOut,currency)}</strong></div></div>
          </section>
          <section className="accounts-panel"><div className="accounts-panel-heading"><h3>Linked transfers <InfoDot label="Linked account transfers">Matched principal only, separate from external cash flow. Pairs are assigned to the month of the outgoing payment, including transfers received in a later month.</InfoDot></h3><small>{periodLabel}</small></div>{routes.length?<div className="accounts-routes">{routes.map(r=><div className="accounts-route" key={r.key}><span><i style={{background:r.fromColor}}/>{data.accounts.find(a=>a.id===r.fromId)?.name||r.from}</span><span className="accounts-route-arrow">→</span><span><i style={{background:r.toColor}}/>{data.accounts.find(a=>a.id===r.toId)?.name||r.to}</span><strong>{money(r.pairs.reduce((n,p)=>n+Math.min(-p.row.amountCents,p.other.amountCents),0),currency)}<small>{r.pairs.length} linked {r.pairs.length===1?"pair":"pairs"}</small></strong></div>)}</div>:<p className="accounts-quiet">No linked transfers in this period.</p>}</section>
        </div><aside className="accounts-side-column">
          <section className="accounts-panel"><div className="accounts-panel-heading"><h3>Account details</h3></div><dl className="accounts-facts"><div><dt>Latest reported balance <InfoDot label="Reported balance">The latest balance supplied by an imported CSV, across all dates in the selected currency. It is not a live bank balance. Conflicting same-day observations are shown individually rather than guessed.</InfoDot></dt><dd>{account.balance.value!==null?money(account.balance.value,currency):account.balance.ambiguous?"Multiple observations":"Not supplied"}</dd>{account.balance.date&&<small>{account.balance.date}</small>}{account.balance.observations.length>0&&<button className="accounts-text-button" onClick={()=>setObservations(true)}>View observations ↗</button>}</div><div><dt>Type</dt><dd>{account.kind||"Not set"}</dd></div><div><dt>Imported history · {currency}</dt><dd>{account.snapshotMonths.length} months · {account.rows.length.toLocaleString()} transactions</dd>{account.rows.length>0&&<small>{account.rows.at(-1).date} — {account.rows[0].date}</small>}</div><div><dt>Filename rule</dt><dd><code>{account.prefixRegex||"Manual assignment"}</code></dd></div></dl><button disabled={busy} className="accounts-delete" aria-label={`Delete ${account.name}`} onClick={()=>setDeleting(account)}>Delete account</button></section>
          <details className="accounts-panel accounts-routing"><summary>Remembered filenames</summary>{data.rules.filter(r=>r.account_id===account.id).map(r=><div key={r.key+r.schema}><code>{r.key}</code><button disabled={busy} onClick={()=>run(()=>api.removeRule(r.key,r.schema,r.account_id),"Filename rule removed.")}>Forget</button></div>)}{!data.rules.some(r=>r.account_id===account.id)&&<p className="accounts-quiet">No remembered filenames.</p>}</details>
        </aside></div>
        <section className="accounts-panel accounts-activity"><div className="accounts-panel-heading"><h3>Activity</h3><small>{recent.length.toLocaleString()} transactions · {periodLabel} · {currency}</small></div>{recent.length?<><div className="accounts-activity-list">{recent.slice(0,limit).map(r=><button key={r.id} onClick={()=>onSource?.(r.id)}><time>{r.date}</time><span>{r.description}<small>{r.review.kind==="transfer"?"Linked transfer":r.amountCents>0?"Money in":"Money out"}</small></span><strong>{r.amountCents>0?"+":"−"}{money(Math.abs(r.amountCents),currency)}</strong><span aria-hidden="true">↗</span></button>)}</div>{recent.length>limit&&<button className="accounts-load" onClick={()=>setLimit(n=>n+20)}>Show more ({recent.length-limit} remaining)</button>}</>:<p className="accounts-quiet">No transactions in this period.</p>}</section>
      </div>}
    </>}
    {!!data.deletedAccounts?.length&&<details className="deleted-accounts accounts-deleted"><summary>Deleted accounts ({data.deletedAccounts.length})</summary>{data.deletedAccounts.map(a=><div key={a.id}><span><i className="dr-account-dot" style={{background:a.color}}/>{a.name}</span><button disabled={busy} aria-label={`Restore ${a.name}`} onClick={()=>run(()=>api.restoreAccount(a.id),"Account restored.")}>Restore</button></div>)}</details>}
    {editing&&<AccountEditor account={editing.id?editing:null} layouts={layouts} history={data.history} busy={busy} run={run} onClose={()=>setEditing(null)} onSnapshots={onSnapshots}/>}
    {deleting&&<AccountDeleteDialog account={deleting} data={data} busy={busy} run={run} onClose={()=>setDeleting(null)}/>}
    {observations&&account&&<WorkspaceModal title="Balance observations" onClose={()=>setObservations(false)}><p>{account.name} · {account.balance.date} · {currency}</p>{account.balance.ambiguous&&<p>These same-day balances differ. No closing balance has been assumed.</p>}<div className="accounts-observations">{account.balance.observations.map(r=><button key={r.id} onClick={()=>{setObservations(false);onSource?.(r.id);}}><span>{r.description}</span><strong>{money(r.balanceCents,currency)}</strong></button>)}</div></WorkspaceModal>}
  </div>;
}
