import {TransactionRuleReuse} from './TransactionRuleReuse.jsx';
import {TransactionTemplateEditor} from './TransactionTemplateEditor.jsx';
import {needsTagging} from '../electron/review/system-tags.mjs';
import React,{useState,useEffect,useRef} from 'react';
import {find,money,total,rest,segments,cap,add,resize,remove,boundary,palette,repayment,paired,mapRecords,templateWeights} from './allocation-model.js';
import {categoryColors} from './category-colors.js';
import {tagType,orderedTags} from '../electron/review/tag-model.mjs';
import {isOther} from '../electron/review/system-tags.mjs';
import {transferPairBand} from '../electron/review/transfer-model.mjs';
import {AllocationBar} from './AllocationBar.jsx';
import {AllocationCategoryStrip} from './AllocationCategoryStrip.jsx';
import './allocation-workspace.css';
import { Icon } from "@derekurban/design-system";
function Amount({label,value,commit}){const [text,setText]=useState((value/100).toFixed(2)),cancel=useRef(false);useEffect(()=>setText((value/100).toFixed(2)),[value]);return <label className="v-amount"><span>$</span><input aria-label={label} inputMode="decimal" value={text} onChange={e=>setText(e.target.value)} onFocus={()=>{cancel.current=false;}} onBlur={()=>{if(!cancel.current)commit(/^\d+(\.\d{0,2})?$/.test(text)?Math.round(Number(text)*100):NaN);setText((value/100).toFixed(2));}} onKeyDown={e=>{if(e.key==='Escape'){cancel.current=true;e.target.blur();}if(e.key==='Enter')e.target.blur();}}/></label>}
export function AllocationWorkspace({data,run,onSource,initialTransaction,embedded=false}){const [state,setState]=useState([]),[entities,setEntities]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[direction,setDirection]=useState('all'),[page,setPage]=useState(0),[id,setId]=useState(initialTransaction||null),[history,setHistory]=useState([]),[adding,setAdding]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState('All'),[active,setActive]=useState(null),[notice,setNotice]=useState(''),[step,setStep]=useState(100),[candidate,setCandidate]=useState(null),[amount,setAmount]=useState(0),[template,setTemplate]=useState(null),[attention,setAttention]=useState(false);
const [ruleRevision,setRuleRevision]=useState(0);
useEffect(()=>{if(initialTransaction)setId(initialTransaction);},[initialTransaction]);
useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
const modal=useRef(),linkTrigger=useRef(),track=useRef(),searchInput=useRef(),drag=useRef(),r=find(state,id)||state[0],parts=r?segments(state,r):[],source=paired(state,id),locked=!!source||!!r?.layers.some(l=>l.kind==='transfer'),received=repayment(state,id);
useEffect(()=>{if(adding){modal.current?.showModal();}else if(modal.current?.open){modal.current.close();linkTrigger.current?.focus();}},[adding]);
const busyRef=useRef(false),generation=useRef(0);
async function load(resetId){const seq=++generation.current;const result=await window.urbanomics.reviewState();if(seq!==generation.current)return;setRuleRevision(n=>n+1);const colors=categoryColors(result.entities);setEntities(colors);setState(previous=>mapRecords(result.records,colors).map(row=>{const old=previous.find(p=>p.id===row.id);return old?.dirty&&row.id!==resetId?{...old,liveVersion:row.version}:row;}));setId(previous=>result.records.some(r=>r.id===previous&&!r.deleted)?previous:result.records.find(r=>!r.deleted&&r.amountCents)?.id);}
useEffect(()=>{if(!busyRef.current)load().catch(e=>setError(e.message));},[data]);
useEffect(()=>()=>{generation.current++;},[]);
const transact=async fn=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{await fn();await load(r.id);setHistory([]);setNotice('Saved to your local ledger.');await run(async()=>true);}catch(e){setError(e.message);}finally{busyRef.current=false;setBusy(false);}};
function save(){return transact(async()=>{if(r.liveVersion!==r.version)throw Error('This transaction changed. Reload it before saving.');const transfer=r.layers.find(l=>l.kind==='transfer');if(r.raw.review.kind==='transfer'){await window.urbanomics.organize([{id:r.id,version:r.version,groups:r.groups}]);}else if(transfer){const target=find(state,transfer.target);await window.urbanomics.linkTransfer(target.id,target.version,r.id,r.version,transferPairBand(target.raw,r.raw),r.groups);}else await window.urbanomics.saveAllocation(r.id,r.version,{tags:r.layers.filter(l=>l.kind==='tag').map(l=>({id:l.target,cents:l.cents})),allocations:r.layers.filter(l=>l.kind==='expense'&&l.cents>0).map(l=>({id:l.target,cents:l.cents})),personId:r.person||'',groups:r.groups});});}
function unlink(){const other=find(state,r.raw.review.transferId);return transact(()=>window.urbanomics.unlinkTransfer(r.id,r.version,other.version));}
function change(fn,message){if(busy)return false;try{const next=state.map(row=>row.id===r.id?structuredClone(row):row);fn(next);find(next,r.id).dirty=true;setHistory(h=>[...h.slice(-39),{id:r.id,row:r}]);setState(next);setNotice(message);setError('');return true;}catch(e){setError(e.message);return false;}}
function select(next){setId(next);setAdding(false);setCandidate(null);setActive(null);setQuery('');setKind('All');}
function captureTemplate(){try{const portions=templateWeights(total(r),r.layers.filter(l=>l.kind==='tag').map(l=>({id:l.target,cents:l.cents})));return {name:r.name.slice(0,70)+' template',matchType:r.raw.aliasId?'aliases':'regex',aliasIds:r.raw.aliasId?[r.raw.aliasId]:[],pattern:'^'+(r.raw.originalDescription||r.name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),direction:r.amount>0?'in':'out',categoryId:'',personId:r.raw.review.assignedPersonId||r.person||'',enabled:true,template:{tags:portions,groups:[],autoReview:false}};}catch(e){return null;}}
function openConnection(type){linkTrigger.current=document.activeElement;setCandidate(null);setQuery('');setKind(type);setAdding(true);}
function choose(c){setCandidate(c);setAmount(c.kind==='transfer'?total(r):Math.min(rest(r),c.max));}
function insert(){if(change(s=>add(s,r.id,candidate.kind,candidate.target,amount,candidate),'Layer added. The rest remains in Unallocated.')){setActive(candidate.kind+':'+candidate.target);setCandidate(null);setAdding(false);}}
if(!r)return <section className="allocation-workspace"><h2>No transactions yet</h2><p>{error||'No transactions to allocate yet. Import an account to get started.'}</p></section>;
const tagChoices=orderedTags(entities.filter(t=>t.kind==='category'&&!isOther(t.id,entities)&&tagType(t)===(r.amount>0?'income':'expense')));
const categories=r.amount>0?[{id:'income',name:'Income',color:tagChoices[0]?.color||'#aaa',tags:tagChoices}]:[...entities.filter(e=>e.kind==='bucket').map(e=>({...e,tags:tagChoices.filter(t=>t.parentId===e.id)})),...(tagChoices.some(t=>!t.parentId)?[{id:'ungrouped',name:'Ungrouped',color:'#aaa',tags:tagChoices.filter(t=>!t.parentId)}]:[])];
function toggleTag(tag){if(r.layers.some(l=>l.id==='tag:'+tag.id)){change(rows=>remove(rows,r.id,'tag:'+tag.id),'Tag removed.');return;}change(rows=>{const row=find(rows,r.id);let cents=rest(row);if(!cents){const largest=row.layers.filter(l=>l.kind==='tag').sort((a,b)=>b.cents-a.cents)[0];if(!largest||largest.cents<2)throw Error('Reduce an existing connection to make room for a tag.');cents=Math.floor(largest.cents/2);largest.cents-=cents;}add(rows,r.id,'tag',tag.id,cents,tag);},'Tag applied to your draft.');}
function toggleEvent(event){change(rows=>{const row=find(rows,r.id);row.groups=row.groups.includes(event.id)?row.groups.filter(id=>id!==event.id):[...row.groups,event.id];row.event=row.groups.map(id=>entities.find(e=>e.id===id)?.name).filter(Boolean).join(', ');},'Event links updated in your draft.');}
let candidates=[];if(!locked&&r.amount>0){if(r.person)candidates.push(...state.filter(t=>!t.deleted&&t.id!==r.id&&cap(state,r,t)>0).map(t=>({kind:'expense',target:t.id,name:t.name,detail:`${t.date} · ${t.account} · ${money(cap(state,r,t),r.currency)} available`,color:t.color,max:cap(state,r,t)})));if(!r.layers.length&&r.canTransfer&&!r.manual)candidates.push(...state.filter(t=>!t.deleted&&t.canTransfer&&t.amount<0&&t.accountId!==r.accountId&&t.currency===r.currency&&!t.dirty&&total(t)>=total(r)&&total(t)<=total(r)*1.1).map(t=>({kind:'transfer',target:t.id,name:t.name,detail:`${t.date} · ${t.account} · ${money(total(t)-total(r),r.currency)} fee`,color:palette.Transfer,max:total(r)})));}candidates=candidates.filter(c=>!r.layers.some(l=>l.id===c.kind+':'+c.target)&&(kind==='All'||c.kind===kind)&&`${c.name} ${c.detail}`.toLowerCase().includes(query.toLowerCase())).slice(0,100);
const eventChoices=entities.filter(e=>e.kind==='group'&&e.name.toLowerCase().includes(query.toLowerCase()));
const filtered=state.filter(x=>!x.deleted&&(!attention||needsTagging(x.raw))&&(direction==='all'||direction==='in'&&x.amount>0||direction==='out'&&x.amount<0)&&`${x.name} ${x.account} ${x.date}`.toLowerCase().includes(search.toLowerCase()));const pageRows=filtered.slice(page*60,page*60+60);
const dividerParts=drag.current?segments(drag.current.base,drag.current.before).map(l=>({...l,cents:parts.find(p=>p.id===l.id)?.cents||0})):parts;
const used=parts.filter(l=>l.kind!=='default').reduce((n,l)=>n+l.cents,0);
function dragStart(e,index){e.preventDefault();track.current.classList.add('dragging');e.currentTarget.setPointerCapture(e.pointerId);drag.current={index,y:e.clientY,base:state,before:r,moved:false};}
function dragMove(e){if(!drag.current)return;const d=drag.current;const delta=Math.round((e.clientY-d.y)/track.current.getBoundingClientRect().height*total(r)/step)*step;const next=d.base.map(row=>row.id===r.id?structuredClone(row):row);boundary(next,r.id,d.index,delta);find(next,r.id).dirty=true;d.moved=true;setState(next);}
function dragEnd(){const completed=drag.current;drag.current=null;track.current?.classList.remove('dragging');if(completed?.moved)setHistory(h=>[...h.slice(-39),{id:completed.before.id,row:completed.before}]);}
return <section className="allocation-workspace v-app"><header className="v-header"><div className="v-brand"><span>{embedded?"Transaction workspace":"Organize"}</span></div><div><button disabled={busy||!history.length} onClick={()=>{const undo=history.at(-1);setState(rows=>rows.map(row=>row.id===undo.id?undo.row:row));setHistory(h=>h.slice(0,-1));setNotice('Draft change undone.');}}>↶ Undo draft</button><button disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></div></header>
{r.raw.review.templateReview==='pending'&&<p className="allocation-template-status">Template applied · check these settings and save to confirm.</p>}{r.raw.review.templateReview==='accepted'&&<p className="allocation-template-status">Auto-reviewed by a transaction template.</p>}{r.legacyScaling&&<p className="allocation-error">This receipt has legacy tags covering its full amount. Saving here applies those tags proportionally to the remainder after its deductions.</p>}{error&&<div className="allocation-error" role="alert">{error}</div>}
{r.liveVersion!==r.version&&<div className="allocation-error">This transaction changed elsewhere. Your draft is preserved. <button disabled={busy} onClick={()=>{setHistory([]);load(r.id).catch(e=>setError(e.message));}}>Reload transaction</button></div>}
<main className="v-workspace"><aside className="v-inbox"><div className="allocation-filters"><input aria-label="Find transactions" placeholder="Find a transaction…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><select aria-label="Money direction" value={direction} onChange={e=>{setDirection(e.target.value);setPage(0);}}><option value="all">All transactions</option><option value="in">Money in</option><option value="out">Money out</option></select><label className="allocation-attention"><input type="checkbox" checked={attention} onChange={e=>{setAttention(e.target.checked);setPage(0);}}/>Needs attention only</label></div><h2>Transactions <span>{filtered.length}</span></h2>{pageRows.map(row=>{const seg=segments(state,row);return <button key={row.id} className={'v-record '+(row.id===id?'selected':'')} onClick={()=>select(row.id)} disabled={busy} aria-label={'Open '+row.name}><span><b>{row.name}</b><strong>{row.amount>0?'+':'−'}{money(total(row),row.currency)}</strong></span><small>{row.account} · {row.date.slice(5)}{row.dirty?' · Draft':''}</small><span className="v-mini" aria-label={'Breakdown for '+row.name}>{seg.filter(l=>l.cents>0).map(l=><i key={l.id} style={{width:l.cents/total(row)*100+'%',background:l.color}}/>)}</span></button>})}<div className="allocation-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.max(1,Math.ceil(filtered.length/60))}</span><button disabled={(page+1)*60>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></aside>
<section className="v-sheet" aria-label="Selected transaction"><div className="v-receipt"><div><span className="v-eyebrow">{r.amount>0?'Money in':'Money out'} · {r.date} </span><h2>{r.name}</h2><p>{r.account}{r.person?' · '+(entities.find(e=>e.id===r.person)?.name||'Person'):''}</p></div><div className="v-total"><strong>{money(total(r),r.currency)}</strong><small>{r.currency} · original amount</small></div></div>
<fieldset className="allocation-controls" disabled={busy}><div className="v-body"><AllocationBar parts={parts} dividerParts={dividerParts} total={total(r)} currency={r.currency} locked={locked} track={track} step={step} setStep={setStep} dragStart={dragStart} dragMove={dragMove} dragEnd={dragEnd} adjust={(i,delta)=>change(s=>boundary(s,id,i,delta),'Boundary adjusted.')}/>
<div className="v-layer-space"><div className="v-section-title"><span>Tags & connections</span><button className="allocation-source" onClick={()=>onSource(r.id)}>Original ↗</button></div><AllocationCategoryStrip key={r.id} groups={categories} selected={r.layers.filter(l=>l.kind==='tag').map(l=>l.target)} disabled={busy||locked} onTag={toggleTag}>
{r.amount>0&&!locked&&<><button className="allocation-connection-button" aria-label="Link expense" onClick={()=>openConnection('expense')}><span aria-hidden="true"><Icon name="receipt" size={16}/></span> Expense</button><button className="allocation-connection-button" aria-label="Link transfer" onClick={()=>openConnection('transfer')}><span aria-hidden="true"><Icon name="arrow-left-right" size={16}/></span> Transfer</button></>}<button className="allocation-connection-button" aria-label="Link event" onClick={()=>openConnection('event')}><span aria-hidden="true"><Icon name="calendar-days" size={16}/></span> Event</button></AllocationCategoryStrip>
{r.groups.length>0&&<div className="allocation-event-chips">{r.groups.map(id=><button key={id} aria-label={'Remove event '+entities.find(e=>e.id===id)?.name} onClick={()=>toggleEvent(entities.find(e=>e.id===id))}>{entities.find(e=>e.id===id)?.name} ×</button>)}</div>}<div className="allocation-group-label">Breakdown</div><div className="v-layers">{[...parts,...(!locked?r.layers.filter(l=>l.cents===0):[])].map(l=><div key={l.id} className={'v-layer '+(active===l.id?'active':'')+(l.kind==='default'?' default':'')} style={{'--tint':l.color}}><i/><div className="v-layer-label"><b>{l.name}</b><small>{l.kind==='expense'?'Deducts from this expense':l.kind==='tag'?(r.amount>0?'Income tag':'Expense tag'):l.kind==='transfer'?'Internal account movement':l.kind==='fee'?'External transfer cost':'Not yet allocated'}</small></div>{l.kind==='default'||locked?<strong>{money(l.cents,r.currency)}</strong>:<Amount label={'Amount for '+l.name} value={l.cents} commit={n=>change(s=>resize(s,id,l.id,n),'Layer amount updated.')}/ >}{l.kind!=='default'&&!source&&r.raw.review.kind!=='transfer'&&<button className="v-remove" aria-label={'Remove '+l.name} onClick={()=>change(s=>remove(s,id,l.id),'Layer removed; its amount returns to Unallocated.')}>×</button>}</div>)}</div>
<div className="v-layer-hint">{source?<><b>Connected to {source.name}</b>{r.raw.review.kind==='transfer'&&<button disabled={busy} onClick={unlink}>Unlink transfer</button>}<button onClick={()=>select(source.id)}>Open the incoming side →</button></>:locked?<><b>This amount is an internal transfer.</b>{r.raw.review.kind==='transfer'&&<button disabled={busy} onClick={unlink}>Unlink transfer</button>}</>:<p>Choose a tag above, then adjust its amount or drag a divider.</p>}</div>
{r.amount<0&&received>0&&<div className="v-recovery"><b>{money(received,r.currency)} repaid · {money(total(r)-received,r.currency)} still fronted</b><p>Your tag layers still describe the original {money(total(r),r.currency)} purchase.</p>{state.filter(x=>x.layers.some(l=>l.kind==='expense'&&l.target===id)).map(x=><button key={x.id} onClick={()=>select(x.id)}>{x.name} ↗</button>)}</div>}
<TransactionRuleReuse transaction={r} entities={entities} capture={captureTemplate} onEdit={setTemplate} revision={ruleRevision}/></div></div></fieldset><footer className="v-footer"><div><b>{money(used,r.currency)} specifically assigned <span>·</span> {money(parts.find(l=>l.id==='other')?.cents||0,r.currency)} Unallocated</b><small>{r.dirty?'Unsaved changes':'Changes save only to this transaction'}</small></div><div className="allocation-save-actions"><button className="v-primary" disabled={busy||r.liveVersion!==r.version||(r.raw.review.kind==='transfer'&&!r.dirty)} onClick={save}>{busy?'Saving…':'Save allocation'}</button></div></footer></section></main><dialog ref={modal} className="allocation-link-modal" aria-labelledby="allocation-link-title" onCancel={()=>setAdding(false)} onClick={e=>{if(e.target===e.currentTarget)setAdding(false);}}><header><div><h2 id="allocation-link-title">{kind==='event'?'Link an event':kind==='transfer'?'Link a transfer':'Link an expense'}</h2><p>{r.name} · {money(total(r),r.currency)}</p></div><button aria-label="Close connections" onClick={()=>setAdding(false)}>×</button></header>
{error&&<p role="alert" className="allocation-error">{error}</p>}
{candidate?<><button className="v-back" onClick={()=>setCandidate(null)}>← Back to connections</button><div className="v-choice"><i style={{background:candidate.color}}/><div><b>{candidate.name}</b><small>{candidate.detail}</small></div></div><div className="v-add-amount"><Amount label="New connection amount" value={amount} commit={n=>setAmount(n)}/><button onClick={()=>setAmount(Math.min(rest(r),candidate.max))}>Use available</button><small>{money(rest(r),r.currency)} unallocated</small></div><button className="v-primary" onClick={insert}>{candidate.kind==='transfer'?'Use transfer & accept fee':'Add expense connection'}</button></>:<><nav className="v-kind-tabs" aria-label="Connection type">{[...(r.amount>0&&!locked?[['expense','Expenses'],['transfer','Transfers']]:[]),['event','Events']].map(([value,label])=><button key={value} className={kind===value?'selected':''} onClick={()=>setKind(value)}>{label}</button>)}</nav><input className="v-search" ref={searchInput} aria-label="Find a connection" placeholder={kind==='event'?'Find an event…':'Find a transaction…'} value={query} onChange={e=>setQuery(e.target.value)}/>{kind==='expense'&&<label className="allocation-person">Who is repaying you?<select aria-label="Repayment person" disabled={r.layers.some(l=>l.kind==='expense')} value={r.person||''} onChange={e=>change(rows=>{find(rows,r.id).person=e.target.value;},'Person selected for repayment limits.')}><option value="">Choose a person</option>{entities.filter(e=>e.kind==='person').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
<div className="v-options">{kind==='event'?eventChoices.map(event=><button key={event.id} aria-pressed={r.groups.includes(event.id)} onClick={()=>toggleEvent(event)}><i style={{background:event.color}}/><span><b>{event.name}</b><small>{event.startDate} — {event.endDate}</small></span><strong><Icon name={r.groups.includes(event.id)?'check':'plus'} size={16}/></strong></button>):candidates.map(c=><button key={c.kind+c.target} onClick={()=>choose(c)}><i style={{background:c.color}}/><span><b>{c.name}</b><small>{c.detail}</small></span><strong>＋</strong></button>)}{!(kind==='event'?eventChoices:candidates).length&&<p>{kind==='expense'&&!r.person?'Choose a person to see expenses they can repay.':kind==='event'?'No events found. Create events in Events.':'No eligible connections match.'}</p>}</div><p className="allocation-link-note">{kind==='event'?'Events add context without changing the allocation.':kind==='expense'?'Connections reduce the selected expense and use this receipt’s unallocated amount.':'Transfers link the whole receipt to another account. Any shortfall is a fee.'}</p></>}
<footer><span>Changes stay in your draft until Save allocation.</span><button onClick={()=>setAdding(false)}>Done</button></footer></dialog>{template&&<TransactionTemplateEditor rule={template} entities={entities} onClose={()=>setTemplate(null)} onSaved={async()=>{setNotice('Template saved. Manage it in Settings → Rules.');await run(async()=>true);}}/>}<div role="status" className="v-toast" hidden={!notice}>{notice}</div></section>;
}

