import React from 'react';
import {money} from './allocation-model.js';
const percent=(amount,total)=>amount>0&&amount/total*100<0.1?'<0.1':(amount/total*100).toFixed(1);
export function AllocationBar({parts,dividerParts,total,currency,locked,track,step,setStep,dragStart,dragMove,dragEnd,adjust}){
 const shown=parts,height=Math.max(300,54+(Math.max(parts.length,dividerParts.length)-1)*57),gap=24/height*100;
 let sum=0;const centers=shown.map(p=>{const center=(sum+p.cents/2)/total*height;sum+=p.cents;return center;});
 const labels=centers.map(n=>Math.max(27,Math.min(height-27,n)));for(let i=1;i<labels.length;i++)labels[i]=Math.max(labels[i],labels[i-1]+57);if(labels.at(-1)>height-27){labels[labels.length-1]=height-27;for(let i=labels.length-2;i>=0;i--)labels[i]=Math.min(labels[i],labels[i+1]-57);}
 const boundaries=dividerParts.slice(0,-1).map((p,i)=>dividerParts.slice(0,i+1).reduce((n,x)=>n+x.cents,0)/total*100);
 const slots=[...boundaries];for(let i=1;i<slots.length;i++)slots[i]=Math.max(slots[i],slots[i-1]+gap);if(slots.at(-1)>100){slots[slots.length-1]=100;for(let i=slots.length-2;i>=0;i--)slots[i]=Math.min(slots[i],slots[i+1]-gap);}
 return <div className="v-vial-column allocation-callouts"><div className="v-scale-top"><span>Allocation</span><b>{money(total,currency)}</b></div><div className="allocation-chart" style={{'--allocation-height':height+'px'}}><div className="v-vial-wrap"><div className="v-vial" ref={track} role="img" aria-label={'Allocation of '+money(total,currency)}>{shown.map(p=><div key={p.id} className="v-liquid" style={{height:p.cents/total*100+'%',background:p.color}} title={p.name+' '+money(p.cents,currency)}/>)}</div>{!locked&&dividerParts.slice(0,-1).map((p,i)=><button key={p.id} className="v-divider" style={{top:slots[i]+'%'}} role="slider" aria-label={'Boundary after '+p.name} aria-valuemin={0} aria-valuemax={p.cents+dividerParts[i+1].cents} aria-valuenow={p.cents} aria-valuetext={money(p.cents,currency)} onPointerDown={e=>dragStart(e,i)} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={dragEnd} onLostPointerCapture={dragEnd} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();adjust(i,(e.key==='ArrowDown'?1:-1)*step);}}}>≡</button>)}</div>
 <svg className="allocation-callout-lines" viewBox={'0 0 40 '+height} preserveAspectRatio="none" aria-hidden="true">{shown.map((p,i)=><path key={p.id} d={'M 0 '+centers[i]+' L 14 '+centers[i]+' L 30 '+labels[i]+' L 40 '+labels[i]}/>)}</svg>
 <div className="allocation-callout-labels">{shown.map((p,i)=><div key={p.id} className="allocation-callout" style={{top:labels[i]}}><b title={p.name}>{p.name}</b><small>{money(p.cents,currency)} · {percent(p.cents,total)}%</small></div>)}</div></div><div className="v-scale-bottom"><span>0%</span><span>{parts.length} layers</span></div>{!locked&&<div className="v-precision"><span>Adjust by</span>{[100,1].map(n=><button key={n} className={step===n?'chosen':''} onClick={()=>setStep(n)}>{n===100?'$1':'1¢'}</button>)}</div>}</div>;
}
