import React,{useEffect,useState} from 'react';
export function editableRule(rule,direction){return {...rule,direction:rule.direction==='any'?direction:rule.direction,scopeNote:rule.direction==='any'?'This rule previously matched both directions. Saving these settings limits it to '+(direction==='in'?'money in.':'money out.'):'',categoryId:'',template:rule.template||{tags:rule.categoryId?[{id:rule.categoryId,weight:10000}]:[],groups:[],autoReview:false}};}
export function RuleSettings({rule,entities,aliases=[]}){
 const name=id=>entities.find(e=>e.id===id)?.name||'Missing definition',tags=rule.template?.tags||(rule.categoryId?[{id:rule.categoryId,weight:10000}]:[]);
 return <div className="reuse-rule-settings"><span>{tags.map(t=>`${name(t.id)} ${t.weight/100}%`).join(' · ')||'No tag mapping'}{rule.personId?' · Person: '+name(rule.personId):''}{rule.template?.groups.length?' · Events: '+rule.template.groups.map(name).join(', '):''}</span><small>{rule.matchType==='aliases'?'Vendors: '+rule.aliasIds.map(id=>aliases.find(a=>a.id===id)?.name||id).join(', '):'Description matches: '+rule.pattern} · {rule.direction==='any'?'Both directions':rule.direction==='in'?'Money in':'Money out'}</small><small>{rule.enabled===false?'Switched off':!rule.template?'Automatically applies settings':rule.template.autoReview?'Applies and auto-reviews':'Applies for manual review'}</small></div>;
}
export function TransactionRuleReuse({transaction,entities,capture,onEdit,revision}){
 const [coverage,setCoverage]=useState(null),[error,setError]=useState(''),[aliases,setAliases]=useState([]);
 useEffect(()=>{let alive=true;setCoverage(null);setError('');Promise.all([window.urbanomics.transactionRuleCoverage(transaction.id),window.urbanomics.aliases()]).then(([c,a])=>{if(alive){setCoverage(c);setAliases(a.rules||[]);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[transaction.id,transaction.version,revision]);
 const current=()=>capture(),open=rule=>{const draft=current();if(draft)onEdit(rule?editableRule(rule,draft.direction):draft);else setError('Check the transaction amounts before reusing these settings.');};
 const matches=coverage?.rules||[],active=matches.filter(r=>r.enabled),conflict=coverage?.decision?.status==='conflict';
 return <section className="transaction-rule-reuse" aria-label="Automation for this transaction"><div className="reuse-heading"><b>Next time</b><span>{error?'Could not check rules':!coverage?'Checking existing rules…':conflict?'Competing rules need attention':active.length?'Automatic settings already exist':matches.length?'A matching rule is switched off':'No automatic settings yet'}</span></div>{error&&<p role="alert">{error}</p>}
 {!matches.length&&coverage&&<><p>Reuse this transaction’s tags and person for future matches.</p><button onClick={()=>open(null)}>Remember these settings</button></>}
 {matches.map(rule=>{const draft=current(),same=draft&&JSON.stringify([...draft.template.tags].sort((a,b)=>a.id.localeCompare(b.id)))===JSON.stringify([...(rule.template?.tags||(rule.categoryId?[{id:rule.categoryId,weight:10000}]:[]))].sort((a,b)=>a.id.localeCompare(b.id)))&&(draft.personId||'')===(rule.personId||'');return <article key={rule.id}><strong>{rule.name}</strong><RuleSettings rule={rule} entities={entities} aliases={aliases}/><div className="reuse-actions"><button onClick={()=>open(rule)}>{rule.enabled?'Review rule':'Review & enable'}</button>{!same&&<button onClick={()=>{const settings=current();if(settings)onEdit({...editableRule(rule,settings.direction),personId:settings.personId,template:{...settings.template,groups:rule.template?.groups||[],autoReview:rule.template?.autoReview||false}});}}>Update with these settings</button>}{same&&<small>These tags and person are already covered.</small>}</div></article>;})}
 {matches.length>0&&<small>Update a matching rule to avoid creating a duplicate. Changes apply to future matches; saved transactions stay as they are.</small>}
 </section>;
}
