import {RuleSettings,editableRule} from './TransactionRuleReuse.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {WorkspaceModal} from './WorkspaceModal.jsx';
import {Alert,ConfirmDialog,Segmented} from './ui.jsx';
import {Recognize} from './recognize.jsx';
import {compileTextRule,decompileTextRule,textMatches} from './import-analysis.mjs';
import {dayLabel} from './format.js';
import './transaction-template.css';
const api=window.urbanomics;
// What each preview status means for the person reading it.
const statusLabel={ready:'Will apply',conflict:'Another rule matches too',protected:'Already decided; left alone',unchanged:'Already matches'};
// Remember a transaction's tags (and person, events) for future imports. The preview runs as you edit.
export function TransactionTemplateEditor({rule,entities,onClose,onSaved,example}){
 const [draft,setDraft]=useState(()=>structuredClone(rule)),[preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false),[aliases,setAliases]=useState([]),[confirmDelete,setConfirmDelete]=useState(false),sequence=useRef(0);
 useEffect(()=>{api.aliases().then(s=>setAliases(s.rules||[])).catch(e=>setError(e.message));},[]);
 function update(key,value){setDraft(s=>({...s,[key]:value}));setPreview(null);}
 useEffect(()=>{const n=++sequence.current;setChecking(true);const t=setTimeout(async()=>{try{const result=await api.previewTransactionRule(draft);if(n===sequence.current){setPreview(result);setError('');}}catch(e){if(n===sequence.current){setError(e.message);setPreview(null);}}finally{if(n===sequence.current)setChecking(false);}},450);return()=>clearTimeout(t);},[JSON.stringify(draft)]);
 async function save(){setBusy(true);setError('');try{await api.saveTransactionRule(draft);await onSaved();onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await api.removeTransactionRule(draft.id,draft.version);await onSaved();onClose();}catch(e){setError(e.message);setBusy(false);setConfirmDelete(false);}}
 const conflicts=preview?.matches.some(m=>m.status==='conflict');
 const left=(10000-draft.template.tags.reduce((n,t)=>n+t.weight,0))/100;
 const sample=example||rule.sample||'';
 return <WorkspaceModal className="template-dialog" title={draft.id?'Update this rule':'Remember these settings'} onClose={()=>!busy&&onClose()} footer={<>{draft.id&&<span className="footer-start"><button className="danger" disabled={busy} onClick={()=>setConfirmDelete(true)}>Delete rule</button></span>}<button disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy||checking||!preview||(draft.enabled!==false&&conflicts)} className="primary" onClick={save}>{draft.id?'Update rule':'Save rule'}</button></>}>
 {error&&<Alert>{error}</Alert>}<fieldset disabled={busy} className="template-fields">
 <p className="template-intro">{draft.id?'Change this rule instead of making another. It affects future imports; saved transactions stay as they are.':'Use these tags and this person the next time a matching transaction is imported. Nothing already saved changes.'}</p>
 {draft.scopeNote&&<Alert tone="info">{draft.scopeNote}</Alert>}
 <label>Rule name<input value={draft.name} maxLength={80} onChange={e=>update('name',e.target.value)}/></label>
 <div className="template-match"><span className="template-label">Match by</span><Segmented label="Match by" value={draft.matchType} onChange={v=>update('matchType',v)} options={[{value:'regex',label:'Bank description'},{value:'aliases',label:'Saved vendors'}]}/><span className="template-direction">{draft.direction==='in'?'Money in only':'Money out only'}</span></div>
 {draft.matchType==='regex'?<Recognize lead="Bank descriptions that" rule={decompileTextRule(draft.pattern)} onChange={r=>update('pattern',compileTextRule(r))} candidates={sample?[{id:'sample',filename:sample}]:[]} test={textMatches} patternFor={compileTextRule} noun={['transaction','transactions']} what="the tags" label="Description text to match"/>:<div className="template-aliases">{aliases.map(a=><label key={a.id}><input type="checkbox" checked={draft.aliasIds.includes(a.id)} onChange={e=>update('aliasIds',e.target.checked?[...draft.aliasIds,a.id]:draft.aliasIds.filter(id=>id!==a.id))}/>{a.name}</label>)}{!aliases.length&&<p className="form-help">No saved vendors yet. Add them under Settings, Aliases.</p>}</div>}
 <h3>Apply</h3><div className="template-portions">{draft.template.tags.map(tag=><label key={tag.id}><span>{entities.find(e=>e.id===tag.id)?.name||'Missing tag'}</span><input aria-label={'Percent for '+(entities.find(e=>e.id===tag.id)?.name||tag.id)} type="number" min="0.01" max="100" step="0.01" value={tag.weight/100} onChange={e=>update('template',{...draft.template,tags:draft.template.tags.map(t=>t.id===tag.id?{...t,weight:Math.round(Number(e.target.value)*100)}:t)})}/><span>%</span></label>)}</div>
 <small>{left>0?`${left.toFixed(2)}% is left unsorted. `:''}Percentages scale to each matching transaction.</small>
 <label>Person<select aria-label="Rule person" value={draft.personId||''} onChange={e=>update('personId',e.target.value)}><option value="">No person</option>{entities.filter(e=>e.kind==='person').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
 <details><summary>Events (optional)</summary><div className="template-aliases">{entities.filter(e=>e.kind==='group').map(e=><label key={e.id}><input type="checkbox" checked={draft.template.groups.includes(e.id)} onChange={ev=>update('template',{...draft.template,groups:ev.target.checked?[...draft.template.groups,e.id]:draft.template.groups.filter(id=>id!==e.id)})}/>{e.name}</label>)}</div></details>
 <label className="template-check"><input type="checkbox" checked={draft.template.autoReview} onChange={e=>update('template',{...draft.template,autoReview:e.target.checked})}/><span><b>Count matches as sorted</b><small>{draft.template.autoReview?'Matching imports are tagged and counted as sorted.':'Matching imports are tagged and wait on the Organize desk for you to confirm.'}</small></span></label>
 <label className="template-check"><input type="checkbox" checked={draft.enabled!==false} onChange={e=>update('enabled',e.target.checked)}/>Use this rule for future imports</label>
 <p className="form-help">Repayments and transfers aren't copied. Decisions already made and other rules' matches are left alone.</p>
 </fieldset>
 <section className="template-preview" aria-live="polite"><h3>{checking||!preview?'Checking which transactions match…':preview.matches.length?`${preview.matches.length} existing ${preview.matches.length===1?'match':'matches'}`:'No existing matches'}</h3>{preview&&<p className="form-help">These are examples from your ledger. Saving affects future imports; to apply it to these, use Apply in Settings, Rules.</p>}{conflicts&&<Alert tone="warning">Another rule matches some of the same transactions. Edit that rule below, make this one more specific, or switch this one off before saving.</Alert>}{preview&&[...preview.matches].sort((a,b)=>Number(b.status==='conflict')-Number(a.status==='conflict')).slice(0,30).map(m=><details key={m.id} open={m.status==='conflict'} className="template-match-detail"><summary><span>{m.description}<small>{dayLabel(m.date)} · {m.account}</small></span><b className={m.status==='conflict'?'is-warn':''}>{statusLabel[m.status]||m.status}</b></summary><p>{m.reason}</p>{m.ruleDetails?.map(r=><article key={r.id}><strong>{r.id===(draft.id||'draft')?'This rule':r.name}</strong><RuleSettings rule={r} entities={entities} aliases={aliases}/>{r.id!==(draft.id||'draft')&&<button className="sm" onClick={()=>{setDraft(editableRule(r,draft.direction));setPreview(null);setError('');}}>Edit {r.name}</button>}</article>)}</details>)}{preview?.matches.length>30&&<small>Showing the first 30. Every match was checked.</small>}</section>
 {confirmDelete&&<ConfirmDialog title={`Delete “${draft.name}”?`} confirmLabel="Delete rule" busy={busy} onClose={()=>setConfirmDelete(false)} onConfirm={remove}><p>Future imports won't be tagged by it. Transactions it already tagged keep their tags.</p></ConfirmDialog>}
 </WorkspaceModal>;
}
