import React,{useMemo,useState} from "react";
import {WorkspaceModal} from "./WorkspaceModal.jsx";
import {FinanceEditor} from "./ReviewWorkspace.jsx";
import {EntityEditor} from "./EntityEditor.jsx";
import {CashReceiptEditor} from "./CashReceiptEditor.jsx";
import {InfoDot,money,monthLabel} from "./snapshots-v2-atoms.jsx";
import {useWorkspaceLedger} from "./workspace-ledger.js";
import {ledgerView} from "./transactions-model.js";
import { Icon } from "@derekurban/design-system";
const emptyReview={kind:"unreviewed",tags:[],groups:[],allocations:[],shares:null};
export function TransactionsWorkspace({data,run,busy,onSource,onOrganize,initialMonth="",initialAccount="",snapshot,onCurrent}){
 const {state,records,entities,error,setError,act}=useWorkspaceLedger(data,run);
 const [filters,setFilters]=useState({month:initialMonth,account:initialAccount,currency:"",flow:"",tag:"",event:"",person:"",status:"",query:"",sort:"date",order:"desc"});
 const [page,setPage]=useState(0),[more,setMore]=useState(false),[compact,setCompact]=useState(false),[original,setOriginal]=useState(false),[selected,setSelected]=useState(null),[personDraft,setPersonDraft]=useState(""),[finance,setFinance]=useState(null),[epoch,setEpoch]=useState(0),[entity,setEntity]=useState(null),[cash,setCash]=useState(null);
 const sourceRows=useMemo(()=>snapshot?snapshot.transactions.map(r=>({...r,review:emptyReview})):records,[snapshot,records]);
 const live=sourceRows.filter(r=>!r.deleted),currencies=[...new Set(live.map(r=>r.currency))].sort();
 const currency=currencies.includes(filters.currency)?filters.currency:currencies.includes("CAD")?"CAD":currencies[0]||"CAD";
 const model=useMemo(()=>ledgerView(records,entities,{...filters,currency},{snapshot:!!snapshot,sourceRows}),[records,entities,filters,currency,sourceRows,snapshot]);
 const pages=Math.max(1,Math.ceil(model.rows.length/50)),currentPage=Math.min(page,pages-1),shown=model.rows.slice(currentPage*50,currentPage*50+50);
 const selectedRow=sourceRows.find(r=>r.id===selected),financeRow=records.find(r=>r.id===finance);
 const tags=entities.filter(e=>e.kind==="category"),events=entities.filter(e=>e.kind==="group"),people=entities.filter(e=>e.kind==="person");
 const change=(key,value)=>{setFilters(f=>({...f,[key]:value}));setPage(0);};
 const sort=key=>{setFilters(f=>({...f,sort:key,order:f.sort===key&&f.order==="desc"?"asc":"desc"}));setPage(0);};
 const organize=row=>{setSelected(null);setFinance(null);onOrganize(row?.id);};
 const openSource=row=>{setSelected(null);setFinance(null);onSource(row.id);};
 return <section className="ledger-workspace workspace-page"><div className="workspace-heading"><div><h1>Transactions</h1></div><div className="workspace-actions">{!snapshot&&<button disabled={busy} onClick={()=>setCash({})}>+ Cash received</button>}<button onClick={()=>onOrganize()}>Organize transactions →</button></div></div>
 {error&&<p className="alert error" role="alert">{error}</p>}
 {snapshot&&<div className="workspace-banner"><span>Saved snapshot · {monthLabel(initialMonth)} · Read only</span><button onClick={onCurrent}>Back to current ledger</button></div>}
 <div className="workspace-stats"><div><strong>{model.rows.length.toLocaleString()}</strong><span>Transactions</span></div><div><strong>{money(model.moneyIn,currency)}</strong><span>{snapshot?"Money in":"External money in"}</span></div><div><strong>{money(model.moneyOut,currency)}</strong><span>{snapshot?"Money out":"External money out"}</span></div><div><strong>{money(model.moneyIn-model.moneyOut,currency)}</strong><span>Net movement <InfoDot label="Transaction totals">Totals reflect the visible filters in {currency}. {snapshot?"Snapshots show the original cash movements, before organization.":"Matched internal transfer principal is excluded, while fees and excess received remain included. Repayments and manual cash are included; this is cash movement, not net spending."}</InfoDot></span></div></div>
 <div className="ledger-controls"><div className="ledger-toolbar"><input aria-label="Search transactions" placeholder="Search names, aliases or bank descriptions…" value={filters.query} onChange={e=>change("query",e.target.value)}/><select aria-label="Transaction month" value={filters.month} onChange={e=>change("month",e.target.value)}><option value="">All months</option>{[...new Set(live.map(r=>r.date.slice(0,7)))].sort().reverse().map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select><select aria-label="Transaction account" value={filters.account} onChange={e=>change("account",e.target.value)}><option value="">All accounts</option>{[...new Map(live.map(r=>[r.accountId||"cash",r.account||"Cash"])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select aria-label="Transaction currency" value={currency} onChange={e=>change("currency",e.target.value)}>{(currencies.length?currencies:[currency]).map(c=><option key={c}>{c}</option>)}</select></div>
 <div className="ledger-toolbar-bottom"><nav className="workspace-tabs" aria-label="Transaction type">{[["","All"],["income","Income"],["expense","Expenses"],...(!snapshot?[["transfer","Transfers"]]:[])].map(([id,label])=><button key={id} aria-pressed={filters.flow===id} onClick={()=>change("flow",id)}>{label}</button>)}</nav><button aria-expanded={more} onClick={()=>setMore(v=>!v)}>Filters & view {more?"−":"+"}</button></div>
 {more&&<div className="ledger-extra">{!snapshot&&<>{[["tag","Tag",tags],["event","Event",events],["person","Person",people]].map(([key,label,list])=><label key={key}>{label}<select aria-label={"Filter by "+label.toLowerCase()} value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">All {label.toLowerCase()}s</option>{list.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>)}<label>Connections<select aria-label="Transaction connections" value={filters.status} onChange={e=>change("status",e.target.value)}><option value="">Any</option><option value="attention">Needs tagging</option><option value="deductions">Has deductions</option><option value="shared">Shared expenses</option></select></label></>}<div className="ledger-display"><label><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>Compact rows</label><label><input type="checkbox" checked={original} onChange={e=>setOriginal(e.target.checked)}/>Original bank text</label></div><button onClick={()=>{setFilters(f=>({...f,query:"",month:"",account:"",flow:"",tag:"",event:"",person:"",status:""}));setPage(0);}}>Clear filters</button></div>}
 </div>
 <div className={"ledger-table-wrap "+(compact?"is-compact":"")}><table className="ledger-table"><thead><tr>{[["date","Date"],["description","Transaction"]].map(([key,label])=><th key={key} aria-sort={filters.sort===key?(filters.order==="asc"?"ascending":"descending"):"none"}><button onClick={()=>sort(key)}>{label} <Icon name={filters.sort===key?(filters.order==="asc"?"arrow-up":"arrow-down"):"arrow-up-down"} size={12} style={{display:"inline-block",verticalAlign:"-1px"}}/></button></th>)}<th>Account</th><th>Connections</th><th aria-sort={filters.sort==="amount"?(filters.order==="asc"?"ascending":"descending"):"none"}><button onClick={()=>sort("amount")}>Amount <Icon name={filters.sort==="amount"?(filters.order==="asc"?"arrow-up":"arrow-down"):"arrow-up-down"} size={12} style={{display:"inline-block",verticalAlign:"-1px"}}/></button></th></tr></thead><tbody>{shown.map(({row:r,flow,tags:rowTags,events:rowEvents,deducted,allocated,needsAttention})=><tr key={r.id}><td><time>{r.date}</time></td><td><button className="ledger-name" onClick={()=>{setPersonDraft(r.review.assignedPersonId||"");setSelected(r.id);setError("");}}>{r.description||"Transaction"}</button>{original&&r.originalDescription&&<small>{r.originalDescription}</small>}<div className="ledger-labels">{flow==="transfer"?<span>Transfer</span>:snapshot?<span>Original record</span>:<>{rowTags.slice(0,3).map((tag,i)=><span key={i}>{tag}</span>)}{rowTags.length>3&&<span>+{rowTags.length-3}</span>}{needsAttention&&<span className="ledger-attention">Needs tagging</span>}</>}</div></td><td><span className="ledger-account"><i style={{background:r.color||"var(--data-neutral)"}}/>{r.account||"Cash"}</span></td><td><div className="ledger-connections">{rowEvents.map((name,i)=><span key={i}>{name}</span>)}{deducted>0&&<span>{money(deducted,currency)} repaid</span>}{allocated>0&&<span>{money(allocated,currency)} allocated</span>}{r.review.shares?.some(p=>p.id!=="me"&&p.cents>0)&&<span>Shared</span>}{flow==="transfer"&&<span>Linked pair</span>}{!rowEvents.length&&!deducted&&!allocated&&flow!=="transfer"&&!r.review.shares&&<small>—</small>}</div></td><td className="ledger-amount">{r.amountCents>0?"+":"−"}{money(Math.abs(r.amountCents),r.currency)}</td></tr>)}</tbody></table>{!shown.length&&<div className="workspace-empty"><h2>{!state?"Loading transactions…":live.length?"No matching transactions":"Your ledger starts with a snapshot."}</h2><p>{live.length?"Adjust the filters to see more of your ledger.":"Imported transactions will appear here."}</p></div>}</div>
 <div className="ledger-pagination"><span>{model.rows.length?currentPage*50+1:0}–{Math.min((currentPage+1)*50,model.rows.length)} of {model.rows.length}</span><div><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Previous</button><span>{currentPage+1} / {pages}</span><button disabled={currentPage+1>=pages} onClick={()=>setPage(currentPage+1)}>Next</button></div></div>
 {selectedRow&&<WorkspaceModal className="ledger-detail-dialog" title="Transaction" onClose={()=>setSelected(null)} footer={<><button onClick={()=>setSelected(null)}>Close</button>{!snapshot&&<button className="primary" onClick={()=>organize(selectedRow)}>Organize transaction →</button>}</>}><div className="ledger-detail-summary"><span>{selectedRow.date} · {selectedRow.account}</span><h2>{selectedRow.description}</h2><strong>{money(selectedRow.amountCents,selectedRow.currency)}</strong></div><div className="ledger-detail-actions">{!selectedRow.manual&&<button onClick={()=>openSource(selectedRow)}>Original file ↗</button>}{!snapshot&&<button onClick={()=>{setFinance(selectedRow.id);setSelected(null);}}>People & financial settings</button>}{!snapshot&&selectedRow.manual&&<button onClick={()=>{setCash(selectedRow);setSelected(null);}}>Edit cash receipt</button>}</div><dl className="ledger-detail-facts"><div><dt>Tags</dt><dd>{selectedRow.review.tags.map(t=>entities.find(e=>e.id===t.id)?.name||"Tag").join(", ")||"Unallocated"}</dd></div><div><dt>Events</dt><dd>{selectedRow.review.groups.map(id=>entities.find(e=>e.id===id)?.name||"Event").join(", ")||"None"}</dd></div><div><dt>Person</dt><dd>{snapshot?"Original record":<><select aria-label="Assigned person" value={personDraft} disabled={busy} onChange={e=>setPersonDraft(e.target.value)}><option value="">Not assigned</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{personDraft!==(selectedRow.review.assignedPersonId||"")&&<button disabled={busy} onClick={()=>act(()=>window.urbanomics.organize([{id:selectedRow.id,version:selectedRow.version,assignedPersonId:personDraft}]))}>Save person</button>}</>}</dd></div></dl>{error&&<p role="alert">{error}</p>}</WorkspaceModal>}
 {financeRow&&<WorkspaceModal title="People & financial settings" onClose={()=>setFinance(null)}><FinanceEditor key={finance+":"+epoch} row={financeRow} records={records} people={people} groups={events} act={act} busy={busy} error={error} onReload={()=>setEpoch(n=>n+1)} onEntity={e=>setEntity(e)} onTags={organize} onSource={id=>{setFinance(null);onSource(id);}} onSaved={()=>setFinance(null)} onCash={r=>{setFinance(null);setCash(r);}} onDeduct={()=>{setFinance(null);onOrganize();}}/></WorkspaceModal>}
 {cash&&<CashReceiptEditor row={cash.id?cash:null} act={act} error={error} onClose={()=>setCash(null)} onSaved={id=>{setCash(null);onOrganize(id);}}/>}
 {entity&&<EntityEditor entity={entity} entities={entities} act={act} error={error} onClose={()=>setEntity(null)}/>}
 </section>;
}
