import {RuleSettings,editableRule} from './TransactionRuleReuse.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {WorkspaceModal} from './WorkspaceModal.jsx';
import './transaction-template.css';
const api=window.urbanomics;
export function TransactionTemplateEditor({rule,entities,onClose,onSaved}){
 const [draft,setDraft]=useState(()=>structuredClone(rule)),[preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[aliases,setAliases]=useState([]),[confirmDelete,setConfirmDelete]=useState(false),sequence=useRef(0),previewRef=useRef(null);
 useEffect(()=>{if(preview)previewRef.current?.scrollIntoView({block:'nearest'});},[preview]);
 useEffect(()=>{api.aliases().then(s=>setAliases(s.rules||[])).catch(e=>setError(e.message));},[]);
 function update(key,value){setDraft(s=>({...s,[key]:value}));setPreview(null);sequence.current++;}
 async function check(){const n=++sequence.current;setBusy(true);setError('');try{const result=await api.previewTransactionRule(draft);if(n===sequence.current)setPreview(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');try{await api.saveTransactionRule(draft);await onSaved();onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <WorkspaceModal className="template-dialog" title={draft.id?'Update automatic settings':'Remember these settings'} onClose={()=>!busy&&onClose()} footer={<div className="template-actions">{draft.id&&<button disabled={busy} onClick={async()=>{if(!confirmDelete){setConfirmDelete(true);return;}setBusy(true);try{await api.removeTransactionRule(draft.id,draft.version);await onSaved();onClose();}catch(e){setError(e.message);setBusy(false);}}}>{confirmDelete?'Confirm delete':'Delete rule'}</button>}<button disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy||!preview||(draft.enabled!==false&&preview.matches.some(m=>m.status==='conflict'))} className="primary" onClick={save}>{draft.id?'Update rule':'Enable for next time'}</button></div>}>
 {error&&<p role="alert" className="template-error">{error}</p>}<fieldset disabled={busy} className="template-fields">
 <p className="template-intro">{draft.id?'Update this rule instead of making another. Its matching scope is shown below; changes affect future matches.':'Reuse these tags and person the next time this vendor appears. Preview what will match before enabling it.'}</p>{draft.scopeNote&&<p className="template-error">{draft.scopeNote}</p>}<label>Rule name<input value={draft.name} maxLength={80} onChange={e=>update('name',e.target.value)}/></label>
 <div className="template-match"><label>Match using<select aria-label="Template match type" value={draft.matchType} onChange={e=>update('matchType',e.target.value)}><option value="regex">Bank description regex</option><option value="aliases">Saved vendors / aliases</option></select></label><span>{draft.direction==='in'?'Money in':'Money out'}</span></div>
 {draft.matchType==='regex'?<label>Description regex<input spellCheck={false} value={draft.pattern} onChange={e=>update('pattern',e.target.value)}/></label>:<div className="template-aliases">{aliases.map(a=><label key={a.id}><input type="checkbox" checked={draft.aliasIds.includes(a.id)} onChange={e=>update('aliasIds',e.target.checked?[...draft.aliasIds,a.id]:draft.aliasIds.filter(id=>id!==a.id))}/>{a.name}</label>)}</div>}
 <h3>Apply these settings</h3><div className="template-portions">{draft.template.tags.map(tag=><label key={tag.id}><span>{entities.find(e=>e.id===tag.id)?.name||'Missing tag'}</span><input aria-label={'Template percent for '+(entities.find(e=>e.id===tag.id)?.name||tag.id)} type="number" min="0.01" max="100" step="0.01" value={tag.weight/100} onChange={e=>update('template',{...draft.template,tags:draft.template.tags.map(t=>t.id===tag.id?{...t,weight:Math.round(Number(e.target.value)*100)}:t)})}/><span>%</span></label>)}</div>
 <small>{((10000-draft.template.tags.reduce((n,t)=>n+t.weight,0))/100).toFixed(2)}% remains unallocated. Percentages scale to each matching transaction.</small>
 <label>Person association<select aria-label="Template person" value={draft.personId||''} onChange={e=>update('personId',e.target.value)}><option value="">No person</option>{entities.filter(e=>e.kind==='person').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
 <details><summary>Event context (optional)</summary><div className="template-aliases">{entities.filter(e=>e.kind==='group').map(e=><label key={e.id}><input type="checkbox" checked={draft.template.groups.includes(e.id)} onChange={ev=>update('template',{...draft.template,groups:ev.target.checked?[...draft.template.groups,e.id]:draft.template.groups.filter(id=>id!==e.id)})}/>{e.name}</label>)}</div></details>
 <label className="template-check"><input type="checkbox" checked={draft.template.autoReview} onChange={e=>update('template',{...draft.template,autoReview:e.target.checked})}/><span><b>Auto-review</b><small>{draft.template.autoReview?'Apply and accept matching imports without manual verification.':'Apply matching settings, then keep the transaction in your attention queue.'}</small></span></label>
 <label className="template-check"><input type="checkbox" checked={draft.enabled!==false} onChange={e=>update('enabled',e.target.checked)}/>Enabled for future imports</label>
 <p>Expense repayments and transfers are not copied. Existing decisions and competing rules are protected.</p><button onClick={check}>Preview matches</button>
 </fieldset>{preview&&<section ref={previewRef} className="template-preview"><h3>{preview.matches.length} existing {preview.matches.length===1?'match':'matches'}</h3><p>Existing transactions are examples. Saving applies to future imports; apply to existing records separately in Settings → Rules.</p>{preview.matches.some(m=>m.status==='conflict')&&<p role="alert" className="template-error">These rules compete for the same transactions. Edit an existing rule below, narrow the matcher, or switch this rule off before saving. No competing match will be applied.</p>}{[...preview.matches].sort((a,b)=>Number(b.status==='conflict')-Number(a.status==='conflict')).slice(0,30).map(m=><details key={m.id} open={m.status==='conflict'} className="template-match-detail"><summary><span>{m.description}<small>{m.date} · {m.account}</small></span><b>{m.status}</b></summary><p>{m.reason}</p>{m.ruleDetails?.map(r=><article key={r.id}><strong>{r.id===(draft.id||'draft')?'This rule':r.name}</strong><RuleSettings rule={r} entities={entities} aliases={aliases}/>{r.id!==(draft.id||'draft')&&<button onClick={()=>{setDraft(editableRule(r,draft.direction));setPreview(null);setError('');sequence.current++;}}>Edit existing rule: {r.name}</button>}</article>)}</details>)}{preview.matches.length>30&&<small>Showing the first 30 matches. All matches were checked.</small>}</section>}

 </WorkspaceModal>;
}
